/*
 * SaladCloud API
 *
 * The SaladCloud REST API. Please refer to the [SaladCloud API Documentation](https://docs.salad.com/api-reference) for more details.
 *
 * The version of the OpenAPI document: 0.9.0-alpha.17
 * Contact: cloud@salad.com
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`create_container_group`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateContainerGroupError {
    Status400(models::ProblemDetails),
    Status403(models::ProblemDetails),
    Status429(models::ProblemDetails),
    DefaultResponse(models::ProblemDetails),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delete_container_group`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteContainerGroupError {
    Status403(models::ProblemDetails),
    Status404(models::ProblemDetails),
    Status429(models::ProblemDetails),
    DefaultResponse(models::ProblemDetails),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_container_group`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetContainerGroupError {
    Status404(models::ProblemDetails),
    Status429(models::ProblemDetails),
    DefaultResponse(models::ProblemDetails),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_container_group_instance`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetContainerGroupInstanceError {
    Status404(models::ProblemDetails),
    Status429(models::ProblemDetails),
    DefaultResponse(models::ProblemDetails),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_container_group_instances`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListContainerGroupInstancesError {
    Status404(models::ProblemDetails),
    Status429(models::ProblemDetails),
    DefaultResponse(models::ProblemDetails),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_container_groups`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListContainerGroupsError {
    Status429(models::ProblemDetails),
    DefaultResponse(models::ProblemDetails),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`reallocate_container_group_instance`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ReallocateContainerGroupInstanceError {
    Status404(models::ProblemDetails),
    Status429(models::ProblemDetails),
    DefaultResponse(models::ProblemDetails),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`recreate_container_group_instance`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RecreateContainerGroupInstanceError {
    Status404(models::ProblemDetails),
    Status429(models::ProblemDetails),
    DefaultResponse(models::ProblemDetails),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`restart_container_group_instance`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RestartContainerGroupInstanceError {
    Status404(models::ProblemDetails),
    Status429(models::ProblemDetails),
    DefaultResponse(models::ProblemDetails),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`start_container_group`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum StartContainerGroupError {
    Status400(models::ProblemDetails),
    Status403(models::ProblemDetails),
    Status429(models::ProblemDetails),
    DefaultResponse(models::ProblemDetails),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`stop_container_group`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum StopContainerGroupError {
    Status400(models::ProblemDetails),
    Status403(models::ProblemDetails),
    Status429(models::ProblemDetails),
    DefaultResponse(models::ProblemDetails),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`update_container_group`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateContainerGroupError {
    Status400(models::ProblemDetails),
    Status403(models::ProblemDetails),
    Status404(models::ProblemDetails),
    Status429(models::ProblemDetails),
    DefaultResponse(models::ProblemDetails),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`update_container_group_instance`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateContainerGroupInstanceError {
    Status400(models::ProblemDetails),
    Status403(models::ProblemDetails),
    Status404(models::ProblemDetails),
    Status429(models::ProblemDetails),
    DefaultResponse(models::ProblemDetails),
    UnknownValue(serde_json::Value),
}


/// Creates a new container group
pub async fn create_container_group(configuration: &configuration::Configuration, organization_name: &str, project_name: &str, container_group_prototype: models::ContainerGroupPrototype) -> Result<models::ContainerGroup, Error<CreateContainerGroupError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_organization_name = organization_name;
    let p_path_project_name = project_name;
    let p_body_container_group_prototype = container_group_prototype;

    let uri_str = format!("{}/organizations/{organization_name}/projects/{project_name}/containers", configuration.base_path, organization_name=crate::apis::urlencode(p_path_organization_name), project_name=crate::apis::urlencode(p_path_project_name));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Salad-Api-Key", value);
    };
    req_builder = req_builder.json(&p_body_container_group_prototype);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ContainerGroup`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ContainerGroup`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CreateContainerGroupError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Deletes a container group
pub async fn delete_container_group(configuration: &configuration::Configuration, organization_name: &str, project_name: &str, container_group_name: &str) -> Result<(), Error<DeleteContainerGroupError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_organization_name = organization_name;
    let p_path_project_name = project_name;
    let p_path_container_group_name = container_group_name;

    let uri_str = format!("{}/organizations/{organization_name}/projects/{project_name}/containers/{container_group_name}", configuration.base_path, organization_name=crate::apis::urlencode(p_path_organization_name), project_name=crate::apis::urlencode(p_path_project_name), container_group_name=crate::apis::urlencode(p_path_container_group_name));
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Salad-Api-Key", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<DeleteContainerGroupError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Gets a container group
pub async fn get_container_group(configuration: &configuration::Configuration, organization_name: &str, project_name: &str, container_group_name: &str) -> Result<models::ContainerGroup, Error<GetContainerGroupError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_organization_name = organization_name;
    let p_path_project_name = project_name;
    let p_path_container_group_name = container_group_name;

    let uri_str = format!("{}/organizations/{organization_name}/projects/{project_name}/containers/{container_group_name}", configuration.base_path, organization_name=crate::apis::urlencode(p_path_organization_name), project_name=crate::apis::urlencode(p_path_project_name), container_group_name=crate::apis::urlencode(p_path_container_group_name));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Salad-Api-Key", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ContainerGroup`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ContainerGroup`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetContainerGroupError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Gets a container group instance
pub async fn get_container_group_instance(configuration: &configuration::Configuration, organization_name: &str, project_name: &str, container_group_name: &str, container_group_instance_id: &str) -> Result<models::ContainerGroupInstance, Error<GetContainerGroupInstanceError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_organization_name = organization_name;
    let p_path_project_name = project_name;
    let p_path_container_group_name = container_group_name;
    let p_path_container_group_instance_id = container_group_instance_id;

    let uri_str = format!("{}/organizations/{organization_name}/projects/{project_name}/containers/{container_group_name}/instances/{container_group_instance_id}", configuration.base_path, organization_name=crate::apis::urlencode(p_path_organization_name), project_name=crate::apis::urlencode(p_path_project_name), container_group_name=crate::apis::urlencode(p_path_container_group_name), container_group_instance_id=crate::apis::urlencode(p_path_container_group_instance_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Salad-Api-Key", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ContainerGroupInstance`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ContainerGroupInstance`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetContainerGroupInstanceError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Gets the list of container group instances
pub async fn list_container_group_instances(configuration: &configuration::Configuration, organization_name: &str, project_name: &str, container_group_name: &str) -> Result<models::ContainerGroupInstanceCollection, Error<ListContainerGroupInstancesError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_organization_name = organization_name;
    let p_path_project_name = project_name;
    let p_path_container_group_name = container_group_name;

    let uri_str = format!("{}/organizations/{organization_name}/projects/{project_name}/containers/{container_group_name}/instances", configuration.base_path, organization_name=crate::apis::urlencode(p_path_organization_name), project_name=crate::apis::urlencode(p_path_project_name), container_group_name=crate::apis::urlencode(p_path_container_group_name));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Salad-Api-Key", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ContainerGroupInstanceCollection`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ContainerGroupInstanceCollection`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ListContainerGroupInstancesError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Gets the list of container groups
pub async fn list_container_groups(configuration: &configuration::Configuration, organization_name: &str, project_name: &str) -> Result<models::ContainerGroupCollection, Error<ListContainerGroupsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_organization_name = organization_name;
    let p_path_project_name = project_name;

    let uri_str = format!("{}/organizations/{organization_name}/projects/{project_name}/containers", configuration.base_path, organization_name=crate::apis::urlencode(p_path_organization_name), project_name=crate::apis::urlencode(p_path_project_name));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Salad-Api-Key", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ContainerGroupCollection`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ContainerGroupCollection`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ListContainerGroupsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Reallocates a container group instance to run on a different Salad Node
pub async fn reallocate_container_group_instance(configuration: &configuration::Configuration, organization_name: &str, project_name: &str, container_group_name: &str, container_group_instance_id: &str) -> Result<(), Error<ReallocateContainerGroupInstanceError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_organization_name = organization_name;
    let p_path_project_name = project_name;
    let p_path_container_group_name = container_group_name;
    let p_path_container_group_instance_id = container_group_instance_id;

    let uri_str = format!("{}/organizations/{organization_name}/projects/{project_name}/containers/{container_group_name}/instances/{container_group_instance_id}/reallocate", configuration.base_path, organization_name=crate::apis::urlencode(p_path_organization_name), project_name=crate::apis::urlencode(p_path_project_name), container_group_name=crate::apis::urlencode(p_path_container_group_name), container_group_instance_id=crate::apis::urlencode(p_path_container_group_instance_id));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Salad-Api-Key", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<ReallocateContainerGroupInstanceError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Stops a container, destroys it, and starts a new one without requiring the image to be downloaded again on a new Salad Node
pub async fn recreate_container_group_instance(configuration: &configuration::Configuration, organization_name: &str, project_name: &str, container_group_name: &str, container_group_instance_id: &str) -> Result<(), Error<RecreateContainerGroupInstanceError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_organization_name = organization_name;
    let p_path_project_name = project_name;
    let p_path_container_group_name = container_group_name;
    let p_path_container_group_instance_id = container_group_instance_id;

    let uri_str = format!("{}/organizations/{organization_name}/projects/{project_name}/containers/{container_group_name}/instances/{container_group_instance_id}/recreate", configuration.base_path, organization_name=crate::apis::urlencode(p_path_organization_name), project_name=crate::apis::urlencode(p_path_project_name), container_group_name=crate::apis::urlencode(p_path_container_group_name), container_group_instance_id=crate::apis::urlencode(p_path_container_group_instance_id));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Salad-Api-Key", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<RecreateContainerGroupInstanceError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Stops a container and restarts it on the same Salad Node
pub async fn restart_container_group_instance(configuration: &configuration::Configuration, organization_name: &str, project_name: &str, container_group_name: &str, container_group_instance_id: &str) -> Result<(), Error<RestartContainerGroupInstanceError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_organization_name = organization_name;
    let p_path_project_name = project_name;
    let p_path_container_group_name = container_group_name;
    let p_path_container_group_instance_id = container_group_instance_id;

    let uri_str = format!("{}/organizations/{organization_name}/projects/{project_name}/containers/{container_group_name}/instances/{container_group_instance_id}/restart", configuration.base_path, organization_name=crate::apis::urlencode(p_path_organization_name), project_name=crate::apis::urlencode(p_path_project_name), container_group_name=crate::apis::urlencode(p_path_container_group_name), container_group_instance_id=crate::apis::urlencode(p_path_container_group_instance_id));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Salad-Api-Key", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<RestartContainerGroupInstanceError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Starts a container group
pub async fn start_container_group(configuration: &configuration::Configuration, organization_name: &str, project_name: &str, container_group_name: &str) -> Result<(), Error<StartContainerGroupError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_organization_name = organization_name;
    let p_path_project_name = project_name;
    let p_path_container_group_name = container_group_name;

    let uri_str = format!("{}/organizations/{organization_name}/projects/{project_name}/containers/{container_group_name}/start", configuration.base_path, organization_name=crate::apis::urlencode(p_path_organization_name), project_name=crate::apis::urlencode(p_path_project_name), container_group_name=crate::apis::urlencode(p_path_container_group_name));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Salad-Api-Key", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<StartContainerGroupError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Stops a container group
pub async fn stop_container_group(configuration: &configuration::Configuration, organization_name: &str, project_name: &str, container_group_name: &str) -> Result<(), Error<StopContainerGroupError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_organization_name = organization_name;
    let p_path_project_name = project_name;
    let p_path_container_group_name = container_group_name;

    let uri_str = format!("{}/organizations/{organization_name}/projects/{project_name}/containers/{container_group_name}/stop", configuration.base_path, organization_name=crate::apis::urlencode(p_path_organization_name), project_name=crate::apis::urlencode(p_path_project_name), container_group_name=crate::apis::urlencode(p_path_container_group_name));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Salad-Api-Key", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<StopContainerGroupError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Updates a container group
pub async fn update_container_group(configuration: &configuration::Configuration, organization_name: &str, project_name: &str, container_group_name: &str, container_group_patch: models::ContainerGroupPatch) -> Result<models::ContainerGroup, Error<UpdateContainerGroupError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_organization_name = organization_name;
    let p_path_project_name = project_name;
    let p_path_container_group_name = container_group_name;
    let p_body_container_group_patch = container_group_patch;

    let uri_str = format!("{}/organizations/{organization_name}/projects/{project_name}/containers/{container_group_name}", configuration.base_path, organization_name=crate::apis::urlencode(p_path_organization_name), project_name=crate::apis::urlencode(p_path_project_name), container_group_name=crate::apis::urlencode(p_path_container_group_name));
    let mut req_builder = configuration.client.request(reqwest::Method::PATCH, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Salad-Api-Key", value);
    };
    req_builder = req_builder.json(&p_body_container_group_patch);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ContainerGroup`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ContainerGroup`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<UpdateContainerGroupError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Updates a container group instance
pub async fn update_container_group_instance(configuration: &configuration::Configuration, organization_name: &str, project_name: &str, container_group_name: &str, container_group_instance_id: &str, container_group_instance_patch: models::ContainerGroupInstancePatch) -> Result<models::ContainerGroupInstance, Error<UpdateContainerGroupInstanceError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_organization_name = organization_name;
    let p_path_project_name = project_name;
    let p_path_container_group_name = container_group_name;
    let p_path_container_group_instance_id = container_group_instance_id;
    let p_body_container_group_instance_patch = container_group_instance_patch;

    let uri_str = format!("{}/organizations/{organization_name}/projects/{project_name}/containers/{container_group_name}/instances/{container_group_instance_id}", configuration.base_path, organization_name=crate::apis::urlencode(p_path_organization_name), project_name=crate::apis::urlencode(p_path_project_name), container_group_name=crate::apis::urlencode(p_path_container_group_name), container_group_instance_id=crate::apis::urlencode(p_path_container_group_instance_id));
    let mut req_builder = configuration.client.request(reqwest::Method::PATCH, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Salad-Api-Key", value);
    };
    req_builder = req_builder.json(&p_body_container_group_instance_patch);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ContainerGroupInstance`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ContainerGroupInstance`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<UpdateContainerGroupInstanceError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

