/*
 * SaladCloud API
 *
 * The SaladCloud REST API. Please refer to the [SaladCloud API Documentation](https://docs.salad.com/api-reference) for more details.
 *
 * The version of the OpenAPI document: 0.9.0-alpha.17
 * Contact: cloud@salad.com
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`query_log_entries`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum QueryLogEntriesError {
    Status400(models::ProblemDetails),
    Status401(models::ProblemDetails),
    Status403(models::ProblemDetails),
    Status404(models::ProblemDetails),
    Status429(models::ProblemDetails),
    DefaultResponse(models::ProblemDetails),
    UnknownValue(serde_json::Value),
}


/// Retrieve a collection of _log entries_ for the _organization_ identified by `{organization_name}` matching the log query.
pub async fn query_log_entries(configuration: &configuration::Configuration, organization_name: &str, log_entry_query: models::LogEntryQuery) -> Result<models::LogEntryCollection, Error<QueryLogEntriesError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_organization_name = organization_name;
    let p_body_log_entry_query = log_entry_query;

    let uri_str = format!("{}/organizations/{organization_name}/log-entries", configuration.base_path, organization_name=crate::apis::urlencode(p_path_organization_name));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Salad-Api-Key", value);
    };
    req_builder = req_builder.json(&p_body_log_entry_query);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::LogEntryCollection`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::LogEntryCollection`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<QueryLogEntriesError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

