/*
 * SaladCloud API
 *
 * The SaladCloud REST API. Please refer to the [SaladCloud API Documentation](https://docs.salad.com/api-reference) for more details.
 *
 * The version of the OpenAPI document: 0.9.0-alpha.17
 * Contact: cloud@salad.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Debug, Clone)]
/// Struct.
pub struct Configuration {
    /// Field.
    pub base_path: String,
    /// Field.
    pub user_agent: Option<String>,
    /// Field.
    pub client: reqwest::Client,
    /// Field.
    pub basic_auth: Option<BasicAuth>,
    /// Field.
    pub oauth_access_token: Option<String>,
    /// Field.
    pub bearer_access_token: Option<String>,
    /// Field.
    pub api_key: Option<ApiKey>,
}

/// Documentation.
pub type BasicAuth = (String, Option<String>);

#[derive(Debug, Clone)]
/// Struct.
pub struct ApiKey {
    /// Field.
    pub prefix: Option<String>,
    /// Field.
    pub key: String,
}

impl Configuration {
    /// Method / Function.
    pub fn new() -> Configuration {
        Configuration::default()
    }
}

impl Default for Configuration {
    fn default() -> Self {
        Configuration {
            base_path: "https://api.salad.com/api/public".to_owned(),
            user_agent: Some("OpenAPI-Generator/0.9.0-alpha.17/saladcloud".to_owned()),
            client: reqwest::Client::new(),
            basic_auth: None,
            oauth_access_token: None,
            bearer_access_token: None,
            api_key: None,
        }
    }
}
