/*
 * SaladCloud API
 *
 * The SaladCloud REST API. Please refer to the [SaladCloud API Documentation](https://docs.salad.com/api-reference) for more details.
 *
 * The version of the OpenAPI document: 0.9.0-alpha.17
 * Contact: cloud@salad.com
 * Generated by: https://openapi-generator.tech
 */

use super::{ContentType, Error, configuration};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};

/// struct for typed errors of method [`create_inference_endpoint_job`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateInferenceEndpointJobError {
    /// Variant.
    Status400(models::ProblemDetails),
    /// Variant.
    Status401(models::ProblemDetails),
    /// Variant.
    Status403(models::ProblemDetails),
    /// Variant.
    Status404(models::ProblemDetails),
    /// Variant.
    Status429(models::ProblemDetails),
    /// Variant.
    DefaultResponse(models::ProblemDetails),
    /// Variant.
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delete_inference_endpoint_job`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteInferenceEndpointJobError {
    /// Variant.
    Status400(models::ProblemDetails),
    /// Variant.
    Status401(models::ProblemDetails),
    /// Variant.
    Status403(models::ProblemDetails),
    /// Variant.
    Status404(models::ProblemDetails),
    /// Variant.
    Status429(models::ProblemDetails),
    /// Variant.
    DefaultResponse(models::ProblemDetails),
    /// Variant.
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_inference_endpoint`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetInferenceEndpointError {
    /// Variant.
    Status401(models::ProblemDetails),
    /// Variant.
    Status403(models::ProblemDetails),
    /// Variant.
    Status404(models::ProblemDetails),
    /// Variant.
    Status429(models::ProblemDetails),
    /// Variant.
    DefaultResponse(models::ProblemDetails),
    /// Variant.
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_inference_endpoint_job`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetInferenceEndpointJobError {
    /// Variant.
    Status401(models::ProblemDetails),
    /// Variant.
    Status403(models::ProblemDetails),
    /// Variant.
    Status404(models::ProblemDetails),
    /// Variant.
    Status429(models::ProblemDetails),
    /// Variant.
    DefaultResponse(models::ProblemDetails),
    /// Variant.
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_inference_endpoint_jobs`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListInferenceEndpointJobsError {
    /// Variant.
    Status400(models::ProblemDetails),
    /// Variant.
    Status401(models::ProblemDetails),
    /// Variant.
    Status403(models::ProblemDetails),
    /// Variant.
    Status404(models::ProblemDetails),
    /// Variant.
    Status429(models::ProblemDetails),
    /// Variant.
    DefaultResponse(models::ProblemDetails),
    /// Variant.
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_inference_endpoints`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListInferenceEndpointsError {
    /// Variant.
    Status400(models::ProblemDetails),
    /// Variant.
    Status401(models::ProblemDetails),
    /// Variant.
    Status403(models::ProblemDetails),
    /// Variant.
    Status404(models::ProblemDetails),
    /// Variant.
    Status429(models::ProblemDetails),
    /// Variant.
    DefaultResponse(models::ProblemDetails),
    /// Variant.
    UnknownValue(serde_json::Value),
}

/// Creates a new inference endpoint job.
pub async fn create_inference_endpoint_job(
    configuration: &configuration::Configuration,
    organization_name: &str,
    inference_endpoint_name: &str,
    inference_endpoint_job_prototype: models::InferenceEndpointJobPrototype,
) -> Result<models::InferenceEndpointJob, Error<CreateInferenceEndpointJobError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_organization_name = organization_name;
    let p_path_inference_endpoint_name = inference_endpoint_name;
    let p_body_inference_endpoint_job_prototype = inference_endpoint_job_prototype;

    let uri_str = format!(
        "{}/organizations/{organization_name}/inference-endpoints/{inference_endpoint_name}/jobs",
        configuration.base_path,
        organization_name = crate::apis::urlencode(p_path_organization_name),
        inference_endpoint_name = crate::apis::urlencode(p_path_inference_endpoint_name)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Salad-Api-Key", value);
    };
    req_builder = req_builder.json(&p_body_inference_endpoint_job_prototype);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `models::InferenceEndpointJob`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `models::InferenceEndpointJob`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CreateInferenceEndpointJobError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Cancels an inference endpoint job.
pub async fn delete_inference_endpoint_job(
    configuration: &configuration::Configuration,
    organization_name: &str,
    inference_endpoint_name: &str,
    inference_endpoint_job_id: &str,
) -> Result<(), Error<DeleteInferenceEndpointJobError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_organization_name = organization_name;
    let p_path_inference_endpoint_name = inference_endpoint_name;
    let p_path_inference_endpoint_job_id = inference_endpoint_job_id;

    let uri_str = format!(
        "{}/organizations/{organization_name}/inference-endpoints/{inference_endpoint_name}/jobs/{inference_endpoint_job_id}",
        configuration.base_path,
        organization_name = crate::apis::urlencode(p_path_organization_name),
        inference_endpoint_name = crate::apis::urlencode(p_path_inference_endpoint_name),
        inference_endpoint_job_id = crate::apis::urlencode(p_path_inference_endpoint_job_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Salad-Api-Key", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<DeleteInferenceEndpointJobError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Gets an inference endpoint.
pub async fn get_inference_endpoint(
    configuration: &configuration::Configuration,
    organization_name: &str,
    inference_endpoint_name: &str,
) -> Result<models::InferenceEndpoint, Error<GetInferenceEndpointError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_organization_name = organization_name;
    let p_path_inference_endpoint_name = inference_endpoint_name;

    let uri_str = format!(
        "{}/organizations/{organization_name}/inference-endpoints/{inference_endpoint_name}",
        configuration.base_path,
        organization_name = crate::apis::urlencode(p_path_organization_name),
        inference_endpoint_name = crate::apis::urlencode(p_path_inference_endpoint_name)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Salad-Api-Key", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `models::InferenceEndpoint`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `models::InferenceEndpoint`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetInferenceEndpointError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Gets an inference endpoint job.
pub async fn get_inference_endpoint_job(
    configuration: &configuration::Configuration,
    organization_name: &str,
    inference_endpoint_name: &str,
    inference_endpoint_job_id: &str,
) -> Result<models::InferenceEndpointJob, Error<GetInferenceEndpointJobError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_organization_name = organization_name;
    let p_path_inference_endpoint_name = inference_endpoint_name;
    let p_path_inference_endpoint_job_id = inference_endpoint_job_id;

    let uri_str = format!(
        "{}/organizations/{organization_name}/inference-endpoints/{inference_endpoint_name}/jobs/{inference_endpoint_job_id}",
        configuration.base_path,
        organization_name = crate::apis::urlencode(p_path_organization_name),
        inference_endpoint_name = crate::apis::urlencode(p_path_inference_endpoint_name),
        inference_endpoint_job_id = crate::apis::urlencode(p_path_inference_endpoint_job_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Salad-Api-Key", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `models::InferenceEndpointJob`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `models::InferenceEndpointJob`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetInferenceEndpointJobError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Lists inference endpoint jobs.
pub async fn list_inference_endpoint_jobs(
    configuration: &configuration::Configuration,
    organization_name: &str,
    inference_endpoint_name: &str,
    page: Option<i32>,
    page_size: Option<i32>,
) -> Result<models::InferenceEndpointJobCollection, Error<ListInferenceEndpointJobsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_organization_name = organization_name;
    let p_path_inference_endpoint_name = inference_endpoint_name;
    let p_query_page = page;
    let p_query_page_size = page_size;

    let uri_str = format!(
        "{}/organizations/{organization_name}/inference-endpoints/{inference_endpoint_name}/jobs",
        configuration.base_path,
        organization_name = crate::apis::urlencode(p_path_organization_name),
        inference_endpoint_name = crate::apis::urlencode(p_path_inference_endpoint_name)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_page {
        req_builder = req_builder.query(&[("page", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_page_size {
        req_builder = req_builder.query(&[("page_size", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Salad-Api-Key", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `models::InferenceEndpointJobCollection`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `models::InferenceEndpointJobCollection`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ListInferenceEndpointJobsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Lists inference endpoints.
pub async fn list_inference_endpoints(
    configuration: &configuration::Configuration,
    organization_name: &str,
    page: Option<i32>,
    page_size: Option<i32>,
) -> Result<models::InferenceEndpointCollection, Error<ListInferenceEndpointsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_organization_name = organization_name;
    let p_query_page = page;
    let p_query_page_size = page_size;

    let uri_str = format!(
        "{}/organizations/{organization_name}/inference-endpoints",
        configuration.base_path,
        organization_name = crate::apis::urlencode(p_path_organization_name)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_page {
        req_builder = req_builder.query(&[("page", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_page_size {
        req_builder = req_builder.query(&[("page_size", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Salad-Api-Key", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `models::InferenceEndpointCollection`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `models::InferenceEndpointCollection`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ListInferenceEndpointsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
