/*
 * SaladCloud API
 *
 * The SaladCloud REST API. Please refer to the [SaladCloud API Documentation](https://docs.salad.com/api-reference) for more details.
 *
 * The version of the OpenAPI document: 0.9.0-alpha.17
 * Contact: cloud@salad.com
 * Generated by: https://openapi-generator.tech
 */

use super::{ContentType, Error, configuration};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};

/// struct for typed errors of method [`get_cpu_availability`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetCpuAvailabilityError {
    /// Variant.
    Status400(models::ProblemDetails),
    /// Variant.
    Status401(models::ProblemDetails),
    /// Variant.
    Status403(models::ProblemDetails),
    /// Variant.
    Status404(models::ProblemDetails),
    /// Variant.
    Status429(models::ProblemDetails),
    /// Variant.
    DefaultResponse(models::ProblemDetails),
    /// Variant.
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_gpu_availability`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetGpuAvailabilityError {
    /// Variant.
    Status400(models::ProblemDetails),
    /// Variant.
    Status401(models::ProblemDetails),
    /// Variant.
    Status403(models::ProblemDetails),
    /// Variant.
    Status404(models::ProblemDetails),
    /// Variant.
    Status429(models::ProblemDetails),
    /// Variant.
    DefaultResponse(models::ProblemDetails),
    /// Variant.
    UnknownValue(serde_json::Value),
}

/// Gets the CPU availability for the given organization
pub async fn get_cpu_availability(
    configuration: &configuration::Configuration,
    organization_name: &str,
    cpu_availability_prototype: models::CpuAvailabilityPrototype,
) -> Result<models::CpuAvailability, Error<GetCpuAvailabilityError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_organization_name = organization_name;
    let p_body_cpu_availability_prototype = cpu_availability_prototype;

    let uri_str = format!(
        "{}/organizations/{organization_name}/availability/sce-cpu-availability",
        configuration.base_path,
        organization_name = crate::apis::urlencode(p_path_organization_name)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Salad-Api-Key", value);
    };
    req_builder = req_builder.json(&p_body_cpu_availability_prototype);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `models::CpuAvailability`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `models::CpuAvailability`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetCpuAvailabilityError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Gets the GPU availability for the given organization
pub async fn get_gpu_availability(
    configuration: &configuration::Configuration,
    organization_name: &str,
    gpu_availability_prototype: models::GpuAvailabilityPrototype,
) -> Result<models::GpuAvailability, Error<GetGpuAvailabilityError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_organization_name = organization_name;
    let p_body_gpu_availability_prototype = gpu_availability_prototype;

    let uri_str = format!(
        "{}/organizations/{organization_name}/availability/sce-gpu-availability",
        configuration.base_path,
        organization_name = crate::apis::urlencode(p_path_organization_name)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Salad-Api-Key", value);
    };
    req_builder = req_builder.json(&p_body_gpu_availability_prototype);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `models::GpuAvailability`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `models::GpuAvailability`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetGpuAvailabilityError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
