/*
 * SaladCloud API
 *
 * The SaladCloud REST API. Please refer to the [SaladCloud API Documentation](https://docs.salad.com/api-reference) for more details.
 *
 * The version of the OpenAPI document: 0.9.0-alpha.17
 * Contact: cloud@salad.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ContainerLoggingSplunk : Configuration settings for forwarding container logs to a Splunk instance.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContainerLoggingSplunk {
    /// The URL of the Splunk HTTP Event Collector (HEC) endpoint.
    #[serde(rename = "host")]
    pub host: String,
    /// The authentication token required to send data to the Splunk HEC endpoint.
    #[serde(rename = "token")]
    pub token: String,
}

impl ContainerLoggingSplunk {
    /// Configuration settings for forwarding container logs to a Splunk instance.
    pub fn new(host: String, token: String) -> ContainerLoggingSplunk {
        ContainerLoggingSplunk {
            host,
            token,
        }
    }
}

