/*
 * SaladCloud API
 *
 * The SaladCloud REST API. Please refer to the [SaladCloud API Documentation](https://docs.salad.com/api-reference) for more details.
 *
 * The version of the OpenAPI document: 0.9.0-alpha.17
 * Contact: cloud@salad.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ContainerLoggingTcp : Configuration for forwarding container logs to a remote TCP endpoint
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContainerLoggingTcp {
    /// The hostname or IP address of the remote TCP logging endpoint
    #[serde(rename = "host")]
    pub host: String,
    /// The port number on which the TCP logging endpoint is listening
    #[serde(rename = "port")]
    pub port: i32,
}

impl ContainerLoggingTcp {
    /// Configuration for forwarding container logs to a remote TCP endpoint
    pub fn new(host: String, port: i32) -> ContainerLoggingTcp {
        ContainerLoggingTcp {
            host,
            port,
        }
    }
}

