/*
 * SaladCloud API
 *
 * The SaladCloud REST API. Please refer to the [SaladCloud API Documentation](https://docs.salad.com/api-reference) for more details.
 *
 * The version of the OpenAPI document: 0.9.0-alpha.17
 * Contact: cloud@salad.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ContainerGroupLivenessProbe : Defines a liveness probe for container groups that determines when to restart a container if it becomes unhealthy
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContainerGroupLivenessProbe {
    #[serde(rename = "exec", skip_serializing_if = "Option::is_none")]
    pub exec: Option<Box<models::ContainerGroupProbeExec>>,
    /// Number of consecutive failures required to consider the probe as failed
    #[serde(rename = "failure_threshold")]
    pub failure_threshold: i32,
    #[serde(rename = "grpc", skip_serializing_if = "Option::is_none")]
    pub grpc: Option<Box<models::ContainerGroupProbeGrpc>>,
    #[serde(rename = "http", skip_serializing_if = "Option::is_none")]
    pub http: Option<Box<models::ContainerGroupProbeHttp>>,
    /// Number of seconds to wait after container start before initiating liveness probes
    #[serde(rename = "initial_delay_seconds")]
    pub initial_delay_seconds: i32,
    /// Frequency in seconds at which the probe should be executed
    #[serde(rename = "period_seconds")]
    pub period_seconds: i32,
    /// Number of consecutive successes required to consider the probe successful
    #[serde(rename = "success_threshold")]
    pub success_threshold: i32,
    #[serde(rename = "tcp", skip_serializing_if = "Option::is_none")]
    pub tcp: Option<Box<models::ContainerGroupProbeTcp>>,
    /// Number of seconds after which the probe times out if no response is received
    #[serde(rename = "timeout_seconds")]
    pub timeout_seconds: i32,
}

impl ContainerGroupLivenessProbe {
    /// Defines a liveness probe for container groups that determines when to restart a container if it becomes unhealthy
    pub fn new(failure_threshold: i32, initial_delay_seconds: i32, period_seconds: i32, success_threshold: i32, timeout_seconds: i32) -> ContainerGroupLivenessProbe {
        ContainerGroupLivenessProbe {
            exec: None,
            failure_threshold,
            grpc: None,
            http: None,
            initial_delay_seconds,
            period_seconds,
            success_threshold,
            tcp: None,
            timeout_seconds,
        }
    }
}

