/*
 * SaladCloud API
 *
 * The SaladCloud REST API. Please refer to the [SaladCloud API Documentation](https://docs.salad.com/api-reference) for more details.
 *
 * The version of the OpenAPI document: 0.9.0-alpha.17
 * Contact: cloud@salad.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ContainerGroupPrototype : Represents a request to create a container group, which manages a collection of container instances with shared configuration and scaling policies
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContainerGroupPrototype {
    /// Determines whether the container group should start automatically when created (true) or remain stopped until manually started (false)
    #[serde(rename = "autostart_policy")]
    pub autostart_policy: bool,
    #[serde(rename = "container")]
    pub container: Box<models::CreateContainer>,
    /// List of countries nodes must be located in. Remove this field to permit nodes from any country.
    #[serde(rename = "country_codes", skip_serializing_if = "Option::is_none")]
    pub country_codes: Option<Vec<models::CountryCode>>,
    /// Human-readable name for the container group that can include spaces and special characters, used for display purposes
    #[serde(rename = "display_name", skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    #[serde(rename = "liveness_probe", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub liveness_probe: Option<Option<Box<models::ContainerGroupLivenessProbe>>>,
    /// Unique identifier for the container group that must follow DNS naming conventions (lowercase alphanumeric with hyphens)
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "networking", skip_serializing_if = "Option::is_none")]
    pub networking: Option<Box<models::CreateContainerGroupNetworking>>,
    #[serde(rename = "queue_autoscaler", skip_serializing_if = "Option::is_none")]
    pub queue_autoscaler: Option<Box<models::ContainerGroupQueueAutoscaler>>,
    #[serde(rename = "queue_connection", skip_serializing_if = "Option::is_none")]
    pub queue_connection: Option<Box<models::ContainerGroupQueueConnection>>,
    #[serde(rename = "readiness_probe", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub readiness_probe: Option<Option<Box<models::ContainerGroupReadinessProbe>>>,
    /// Number of container instances to deploy and maintain for this container group
    #[serde(rename = "replicas")]
    pub replicas: i32,
    #[serde(rename = "restart_policy")]
    pub restart_policy: models::ContainerRestartPolicy,
    /// List of scaling action configurations
    #[serde(rename = "scaling-actions", skip_serializing_if = "Option::is_none")]
    pub scaling_actions: Option<Vec<models::ContainerGroupScalingAction>>,
    /// Indicates if scheduled scaling is enabled
    #[serde(rename = "scheduled-scaling-enabled", skip_serializing_if = "Option::is_none")]
    pub scheduled_scaling_enabled: Option<bool>,
    #[serde(rename = "startup_probe", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub startup_probe: Option<Option<Box<models::ContainerGroupStartupProbe>>>,
}

impl ContainerGroupPrototype {
    /// Represents a request to create a container group, which manages a collection of container instances with shared configuration and scaling policies
    pub fn new(autostart_policy: bool, container: models::CreateContainer, name: String, replicas: i32, restart_policy: models::ContainerRestartPolicy) -> ContainerGroupPrototype {
        ContainerGroupPrototype {
            autostart_policy,
            container: Box::new(container),
            country_codes: None,
            display_name: None,
            liveness_probe: None,
            name,
            networking: None,
            queue_autoscaler: None,
            queue_connection: None,
            readiness_probe: None,
            replicas,
            restart_policy,
            scaling_actions: None,
            scheduled_scaling_enabled: None,
            startup_probe: None,
        }
    }
}

