/*
 * SaladCloud API
 *
 * The SaladCloud REST API. Please refer to the [SaladCloud API Documentation](https://docs.salad.com/api-reference) for more details.
 *
 * The version of the OpenAPI document: 0.9.0-alpha.17
 * Contact: cloud@salad.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ContainerGroupProbeTcp : Configuration for a TCP probe used to check container health via network connectivity.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContainerGroupProbeTcp {
    /// The TCP port number that the probe should connect to. Must be a valid port number between 0 and 65535.
    #[serde(rename = "port")]
    pub port: i32,
}

impl ContainerGroupProbeTcp {
    /// Configuration for a TCP probe used to check container health via network connectivity.
    pub fn new(port: i32) -> ContainerGroupProbeTcp {
        ContainerGroupProbeTcp {
            port,
        }
    }
}

