/*
 * SaladCloud API
 *
 * The SaladCloud REST API. Please refer to the [SaladCloud API Documentation](https://docs.salad.com/api-reference) for more details.
 *
 * The version of the OpenAPI document: 0.9.0-alpha.17
 * Contact: cloud@salad.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ContainerGroupStatus : Represents the current operational state of a container group within the Salad platform.
/// Represents the current operational state of a container group within the Salad platform.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ContainerGroupStatus {
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "running")]
    Running,
    #[serde(rename = "stopped")]
    Stopped,
    #[serde(rename = "succeeded")]
    Succeeded,
    #[serde(rename = "failed")]
    Failed,
    #[serde(rename = "deploying")]
    Deploying,

}

impl std::fmt::Display for ContainerGroupStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Pending => write!(f, "pending"),
            Self::Running => write!(f, "running"),
            Self::Stopped => write!(f, "stopped"),
            Self::Succeeded => write!(f, "succeeded"),
            Self::Failed => write!(f, "failed"),
            Self::Deploying => write!(f, "deploying"),
        }
    }
}

impl Default for ContainerGroupStatus {
    fn default() -> ContainerGroupStatus {
        Self::Pending
    }
}

