/*
 * SaladCloud API
 *
 * The SaladCloud REST API. Please refer to the [SaladCloud API Documentation](https://docs.salad.com/api-reference) for more details.
 *
 * The version of the OpenAPI document: 0.9.0-alpha.17
 * Contact: cloud@salad.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ContainerGroupInstancePatch : Represents a request to update a container group instance
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContainerGroupInstancePatch {
    /// The cost of deleting the container group instance
    #[serde(rename = "deletion_cost", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub deletion_cost: Option<Option<i32>>,
}

impl ContainerGroupInstancePatch {
    /// Represents a request to update a container group instance
    pub fn new() -> ContainerGroupInstancePatch {
        ContainerGroupInstancePatch {
            deletion_cost: None,
        }
    }
}

