/*
 * SaladCloud API
 *
 * The SaladCloud REST API. Please refer to the [SaladCloud API Documentation](https://docs.salad.com/api-reference) for more details.
 *
 * The version of the OpenAPI document: 0.9.0-alpha.17
 * Contact: cloud@salad.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ContainerGroupsQuotas : Represents the organization quotas for container groups
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContainerGroupsQuotas {
    /// The maximum number of replicas that can be created for a container group
    #[serde(rename = "container_replicas_quota")]
    pub container_replicas_quota: i32,
    /// The number of replicas that are currently in use
    #[serde(rename = "container_replicas_used")]
    pub container_replicas_used: i32,
    /// The maximum number of container group reallocations per minute
    #[serde(rename = "max_container_group_reallocations_per_minute", skip_serializing_if = "Option::is_none")]
    pub max_container_group_reallocations_per_minute: Option<i32>,
    /// The maximum number of container group recreates per minute
    #[serde(rename = "max_container_group_recreates_per_minute", skip_serializing_if = "Option::is_none")]
    pub max_container_group_recreates_per_minute: Option<i32>,
    /// The maximum number of container group restarts per minute
    #[serde(rename = "max_container_group_restarts_per_minute", skip_serializing_if = "Option::is_none")]
    pub max_container_group_restarts_per_minute: Option<i32>,
}

impl ContainerGroupsQuotas {
    /// Represents the organization quotas for container groups
    pub fn new(container_replicas_quota: i32, container_replicas_used: i32) -> ContainerGroupsQuotas {
        ContainerGroupsQuotas {
            container_replicas_quota,
            container_replicas_used,
            max_container_group_reallocations_per_minute: None,
            max_container_group_recreates_per_minute: None,
            max_container_group_restarts_per_minute: None,
        }
    }
}

