/*
 * SaladCloud API
 *
 * The SaladCloud REST API. Please refer to the [SaladCloud API Documentation](https://docs.salad.com/api-reference) for more details.
 *
 * The version of the OpenAPI document: 0.9.0-alpha.17
 * Contact: cloud@salad.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ContainerGroupReadinessProbe : Defines how to check if a container is ready to serve traffic. The readiness probe determines whether the container's application is ready to accept traffic. If the readiness probe fails, the container is considered not ready and traffic will not be sent to it.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContainerGroupReadinessProbe {
    #[serde(rename = "exec", skip_serializing_if = "Option::is_none")]
    pub exec: Option<Box<models::ContainerGroupProbeExec>>,
    /// The number of consecutive failures required to consider the probe failed. After this many consecutive failures, the container is marked as not ready.
    #[serde(rename = "failure_threshold")]
    pub failure_threshold: i32,
    #[serde(rename = "grpc", skip_serializing_if = "Option::is_none")]
    pub grpc: Option<Box<models::ContainerGroupProbeGrpc>>,
    #[serde(rename = "http", skip_serializing_if = "Option::is_none")]
    pub http: Option<Box<models::ContainerGroupProbeHttp>>,
    /// The time in seconds to wait after the container starts before initiating the first probe. This allows time for the application to initialize before being tested.
    #[serde(rename = "initial_delay_seconds")]
    pub initial_delay_seconds: i32,
    /// How frequently (in seconds) the probe should be executed during the container's lifetime. Specifies the interval between consecutive probe executions.
    #[serde(rename = "period_seconds")]
    pub period_seconds: i32,
    /// The minimum consecutive successes required to consider the probe successful after it has failed. Defines how many successful probe results are needed to transition from failure to success.
    #[serde(rename = "success_threshold")]
    pub success_threshold: i32,
    #[serde(rename = "tcp", skip_serializing_if = "Option::is_none")]
    pub tcp: Option<Box<models::ContainerGroupProbeTcp>>,
    /// The maximum time in seconds that the probe has to complete. If the probe doesn't return a result before the timeout, it's considered failed.
    #[serde(rename = "timeout_seconds")]
    pub timeout_seconds: i32,
}

impl ContainerGroupReadinessProbe {
    /// Defines how to check if a container is ready to serve traffic. The readiness probe determines whether the container's application is ready to accept traffic. If the readiness probe fails, the container is considered not ready and traffic will not be sent to it.
    pub fn new(failure_threshold: i32, initial_delay_seconds: i32, period_seconds: i32, success_threshold: i32, timeout_seconds: i32) -> ContainerGroupReadinessProbe {
        ContainerGroupReadinessProbe {
            exec: None,
            failure_threshold,
            grpc: None,
            http: None,
            initial_delay_seconds,
            period_seconds,
            success_threshold,
            tcp: None,
            timeout_seconds,
        }
    }
}

