/*
 * SaladCloud API
 *
 * The SaladCloud REST API. Please refer to the [SaladCloud API Documentation](https://docs.salad.com/api-reference) for more details.
 *
 * The version of the OpenAPI document: 0.9.0-alpha.17
 * Contact: cloud@salad.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ContainerGroupProbeGrpc : Configuration for gRPC-based health probes in container groups, used to determine container health status.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContainerGroupProbeGrpc {
    /// The port number on which the gRPC health check service is exposed.
    #[serde(rename = "port")]
    pub port: i32,
    /// The name of the gRPC service that implements the health check protocol.
    #[serde(rename = "service")]
    pub service: String,
}

impl ContainerGroupProbeGrpc {
    /// Configuration for gRPC-based health probes in container groups, used to determine container health status.
    pub fn new(port: i32, service: String) -> ContainerGroupProbeGrpc {
        ContainerGroupProbeGrpc {
            port,
            service,
        }
    }
}

