/*
 * SaladCloud API
 *
 * The SaladCloud REST API. Please refer to the [SaladCloud API Documentation](https://docs.salad.com/api-reference) for more details.
 *
 * The version of the OpenAPI document: 0.9.0-alpha.17
 * Contact: cloud@salad.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ContainerRestartPolicy : Specifies the policy for restarting containers when they exit or fail.
/// Specifies the policy for restarting containers when they exit or fail.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ContainerRestartPolicy {
    #[serde(rename = "always")]
    Always,
    #[serde(rename = "on_failure")]
    OnFailure,
    #[serde(rename = "never")]
    Never,

}

impl std::fmt::Display for ContainerRestartPolicy {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Always => write!(f, "always"),
            Self::OnFailure => write!(f, "on_failure"),
            Self::Never => write!(f, "never"),
        }
    }
}

impl Default for ContainerRestartPolicy {
    fn default() -> ContainerRestartPolicy {
        Self::Always
    }
}

