/*
 * SaladCloud API
 *
 * The SaladCloud REST API. Please refer to the [SaladCloud API Documentation](https://docs.salad.com/api-reference) for more details.
 *
 * The version of the OpenAPI document: 0.9.0-alpha.17
 * Contact: cloud@salad.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ContainerGroupProbeExec : Defines the exec action for a probe in a container group. This is used to execute a command inside a container for health checks.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContainerGroupProbeExec {
    /// The command to execute inside the container. Exit status of 0 is considered successful, any other exit status is considered failure.
    #[serde(rename = "command")]
    pub command: Vec<String>,
}

impl ContainerGroupProbeExec {
    /// Defines the exec action for a probe in a container group. This is used to execute a command inside a container for health checks.
    pub fn new(command: Vec<String>) -> ContainerGroupProbeExec {
        ContainerGroupProbeExec {
            command,
        }
    }
}

