/*
 * SaladCloud API
 *
 * The SaladCloud REST API. Please refer to the [SaladCloud API Documentation](https://docs.salad.com/api-reference) for more details.
 *
 * The version of the OpenAPI document: 0.9.0-alpha.17
 * Contact: cloud@salad.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ContainerGroupQueueAutoscaler : Defines configuration for automatically scaling container instances based on queue length. The autoscaler monitors a queue and adjusts the number of running replicas to maintain the desired queue length.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContainerGroupQueueAutoscaler {
    /// The target number of items in the queue that the autoscaler attempts to maintain by scaling the containers up or down
    #[serde(rename = "desired_queue_length")]
    pub desired_queue_length: i32,
    /// The maximum number of instances that can be removed per minute to prevent rapid downscaling
    #[serde(rename = "max_downscale_per_minute", skip_serializing_if = "Option::is_none")]
    pub max_downscale_per_minute: Option<i32>,
    /// The maximum number of instances the container can scale up to
    #[serde(rename = "max_replicas")]
    pub max_replicas: i32,
    /// The maximum number of instances that can be added per minute to prevent rapid upscaling
    #[serde(rename = "max_upscale_per_minute", skip_serializing_if = "Option::is_none")]
    pub max_upscale_per_minute: Option<i32>,
    /// The minimum number of instances the container can scale down to, ensuring baseline availability
    #[serde(rename = "min_replicas")]
    pub min_replicas: i32,
    /// The period (in seconds) in which the autoscaler checks the queue length and applies the scaling formula
    #[serde(rename = "polling_period", skip_serializing_if = "Option::is_none")]
    pub polling_period: Option<i32>,
}

impl ContainerGroupQueueAutoscaler {
    /// Defines configuration for automatically scaling container instances based on queue length. The autoscaler monitors a queue and adjusts the number of running replicas to maintain the desired queue length.
    pub fn new(desired_queue_length: i32, max_replicas: i32, min_replicas: i32) -> ContainerGroupQueueAutoscaler {
        ContainerGroupQueueAutoscaler {
            desired_queue_length,
            max_downscale_per_minute: None,
            max_replicas,
            max_upscale_per_minute: None,
            min_replicas,
            polling_period: None,
        }
    }
}

