/*
 * SaladCloud API
 *
 * The SaladCloud REST API. Please refer to the [SaladCloud API Documentation](https://docs.salad.com/api-reference) for more details.
 *
 * The version of the OpenAPI document: 0.9.0-alpha.17
 * Contact: cloud@salad.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ContainerGroupInstanceCollection : A collection of container group instances returned as part of a paginated response or batch operation result.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContainerGroupInstanceCollection {
    /// An array of container group instances, each representing a deployed container group with its current state and configuration information.
    #[serde(rename = "instances")]
    pub instances: Vec<models::ContainerGroupInstance>,
}

impl ContainerGroupInstanceCollection {
    /// A collection of container group instances returned as part of a paginated response or batch operation result.
    pub fn new(instances: Vec<models::ContainerGroupInstance>) -> ContainerGroupInstanceCollection {
        ContainerGroupInstanceCollection {
            instances,
        }
    }
}

