/*
 * SaladCloud API
 *
 * The SaladCloud REST API. Please refer to the [SaladCloud API Documentation](https://docs.salad.com/api-reference) for more details.
 *
 * The version of the OpenAPI document: 0.9.0-alpha.17
 * Contact: cloud@salad.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ContainerRegistryAuthenticationGcpGcr : Authentication details for Google Container Registry (GCR)
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContainerRegistryAuthenticationGcpGcr {
    /// GCP service account key in JSON format for GCR authentication
    #[serde(rename = "service_key")]
    pub service_key: String,
}

impl ContainerRegistryAuthenticationGcpGcr {
    /// Authentication details for Google Container Registry (GCR)
    pub fn new(service_key: String) -> ContainerRegistryAuthenticationGcpGcr {
        ContainerRegistryAuthenticationGcpGcr {
            service_key,
        }
    }
}

