/*
 * SaladCloud API
 *
 * The SaladCloud REST API. Please refer to the [SaladCloud API Documentation](https://docs.salad.com/api-reference) for more details.
 *
 * The version of the OpenAPI document: 0.9.0-alpha.17
 * Contact: cloud@salad.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ContainerLoggingHttpHeader : Represents an HTTP header used for container logging configuration.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContainerLoggingHttpHeader {
    /// The name of the HTTP header
    #[serde(rename = "name")]
    pub name: String,
    /// The value of the HTTP header
    #[serde(rename = "value")]
    pub value: String,
}

impl ContainerLoggingHttpHeader {
    /// Represents an HTTP header used for container logging configuration.
    pub fn new(name: String, value: String) -> ContainerLoggingHttpHeader {
        ContainerLoggingHttpHeader {
            name,
            value,
        }
    }
}

