/*
 * SaladCloud API
 *
 * The SaladCloud REST API. Please refer to the [SaladCloud API Documentation](https://docs.salad.com/api-reference) for more details.
 *
 * The version of the OpenAPI document: 0.9.0-alpha.17
 * Contact: cloud@salad.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ContainerLoggingDatadog : Configuration for forwarding container logs to Datadog monitoring service.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContainerLoggingDatadog {
    /// The Datadog API key used for authentication when sending logs.
    #[serde(rename = "api_key")]
    pub api_key: String,
    /// The Datadog intake server host URL where logs will be sent.
    #[serde(rename = "host")]
    pub host: String,
    /// Optional metadata tags to attach to logs for filtering and categorization in Datadog.
    #[serde(rename = "tags", deserialize_with = "Option::deserialize")]
    pub tags: Option<Vec<models::ContainerLoggingDatadogTag>>,
}

impl ContainerLoggingDatadog {
    /// Configuration for forwarding container logs to Datadog monitoring service.
    pub fn new(api_key: String, host: String, tags: Option<Vec<models::ContainerLoggingDatadogTag>>) -> ContainerLoggingDatadog {
        ContainerLoggingDatadog {
            api_key,
            host,
            tags,
        }
    }
}

