/*
 * SaladCloud API
 *
 * The SaladCloud REST API. Please refer to the [SaladCloud API Documentation](https://docs.salad.com/api-reference) for more details.
 *
 * The version of the OpenAPI document: 0.9.0-alpha.17
 * Contact: cloud@salad.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ContainerGroupNetworkingLoadBalancer : The container group networking load balancer.
/// The container group networking load balancer.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ContainerGroupNetworkingLoadBalancer {
    #[serde(rename = "round_robin")]
    RoundRobin,
    #[serde(rename = "least_number_of_connections")]
    LeastNumberOfConnections,

}

impl std::fmt::Display for ContainerGroupNetworkingLoadBalancer {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::RoundRobin => write!(f, "round_robin"),
            Self::LeastNumberOfConnections => write!(f, "least_number_of_connections"),
        }
    }
}

impl Default for ContainerGroupNetworkingLoadBalancer {
    fn default() -> ContainerGroupNetworkingLoadBalancer {
        Self::RoundRobin
    }
}

