/*
 * SaladCloud API
 *
 * The SaladCloud REST API. Please refer to the [SaladCloud API Documentation](https://docs.salad.com/api-reference) for more details.
 *
 * The version of the OpenAPI document: 0.9.0-alpha.17
 * Contact: cloud@salad.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ContainerGroupCollection : A paginated collection of container groups that provides a structured way to access multiple container group resources in a single response.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContainerGroupCollection {
    /// An array containing container group objects. Each object represents a discrete container group with its own properties, configuration, and status.
    #[serde(rename = "items")]
    pub items: Vec<models::ContainerGroup>,
}

impl ContainerGroupCollection {
    /// A paginated collection of container groups that provides a structured way to access multiple container group resources in a single response.
    pub fn new(items: Vec<models::ContainerGroup>) -> ContainerGroupCollection {
        ContainerGroupCollection {
            items,
        }
    }
}

