/*
 * SaladCloud API
 *
 * The SaladCloud REST API. Please refer to the [SaladCloud API Documentation](https://docs.salad.com/api-reference) for more details.
 *
 * The version of the OpenAPI document: 0.9.0-alpha.17
 * Contact: cloud@salad.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ContainerRegistryAuthenticationGcpGar : Authentication details for Google Artifact Registry (GAR)
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContainerRegistryAuthenticationGcpGar {
    /// GCP service account key in JSON format for GAR authentication
    #[serde(rename = "service_key")]
    pub service_key: String,
}

impl ContainerRegistryAuthenticationGcpGar {
    /// Authentication details for Google Artifact Registry (GAR)
    pub fn new(service_key: String) -> ContainerRegistryAuthenticationGcpGar {
        ContainerRegistryAuthenticationGcpGar {
            service_key,
        }
    }
}

