/*
 * SaladCloud API
 *
 * The SaladCloud REST API. Please refer to the [SaladCloud API Documentation](https://docs.salad.com/api-reference) for more details.
 *
 * The version of the OpenAPI document: 0.9.0-alpha.17
 * Contact: cloud@salad.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CountryCode : ISO 3166-1 alpha-2 country code
/// ISO 3166-1 alpha-2 country code
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CountryCode {
    #[serde(rename = "af")]
    Af,
    #[serde(rename = "al")]
    Al,
    #[serde(rename = "dz")]
    Dz,
    #[serde(rename = "as")]
    As,
    #[serde(rename = "ad")]
    Ad,
    #[serde(rename = "ao")]
    Ao,
    #[serde(rename = "ai")]
    Ai,
    #[serde(rename = "aq")]
    Aq,
    #[serde(rename = "ag")]
    Ag,
    #[serde(rename = "ar")]
    Ar,
    #[serde(rename = "am")]
    Am,
    #[serde(rename = "aw")]
    Aw,
    #[serde(rename = "au")]
    Au,
    #[serde(rename = "at")]
    At,
    #[serde(rename = "az")]
    Az,
    #[serde(rename = "bs")]
    Bs,
    #[serde(rename = "bh")]
    Bh,
    #[serde(rename = "bd")]
    Bd,
    #[serde(rename = "bb")]
    Bb,
    #[serde(rename = "by")]
    By,
    #[serde(rename = "be")]
    Be,
    #[serde(rename = "bz")]
    Bz,
    #[serde(rename = "bj")]
    Bj,
    #[serde(rename = "bm")]
    Bm,
    #[serde(rename = "bt")]
    Bt,
    #[serde(rename = "bo")]
    Bo,
    #[serde(rename = "bq")]
    Bq,
    #[serde(rename = "ba")]
    Ba,
    #[serde(rename = "bw")]
    Bw,
    #[serde(rename = "bv")]
    Bv,
    #[serde(rename = "br")]
    Br,
    #[serde(rename = "io")]
    Io,
    #[serde(rename = "bn")]
    Bn,
    #[serde(rename = "bg")]
    Bg,
    #[serde(rename = "bf")]
    Bf,
    #[serde(rename = "bi")]
    Bi,
    #[serde(rename = "cv")]
    Cv,
    #[serde(rename = "kh")]
    Kh,
    #[serde(rename = "cm")]
    Cm,
    #[serde(rename = "ca")]
    Ca,
    #[serde(rename = "ky")]
    Ky,
    #[serde(rename = "cf")]
    Cf,
    #[serde(rename = "td")]
    Td,
    #[serde(rename = "cl")]
    Cl,
    #[serde(rename = "cn")]
    Cn,
    #[serde(rename = "cx")]
    Cx,
    #[serde(rename = "cc")]
    Cc,
    #[serde(rename = "co")]
    Co,
    #[serde(rename = "km")]
    Km,
    #[serde(rename = "cd")]
    Cd,
    #[serde(rename = "cg")]
    Cg,
    #[serde(rename = "ck")]
    Ck,
    #[serde(rename = "cr")]
    Cr,
    #[serde(rename = "hr")]
    Hr,
    #[serde(rename = "cu")]
    Cu,
    #[serde(rename = "cw")]
    Cw,
    #[serde(rename = "cy")]
    Cy,
    #[serde(rename = "cz")]
    Cz,
    #[serde(rename = "ci")]
    Ci,
    #[serde(rename = "dk")]
    Dk,
    #[serde(rename = "dj")]
    Dj,
    #[serde(rename = "dm")]
    Dm,
    #[serde(rename = "do")]
    Do,
    #[serde(rename = "ec")]
    Ec,
    #[serde(rename = "eg")]
    Eg,
    #[serde(rename = "sv")]
    Sv,
    #[serde(rename = "gq")]
    Gq,
    #[serde(rename = "er")]
    Er,
    #[serde(rename = "ee")]
    Ee,
    #[serde(rename = "sz")]
    Sz,
    #[serde(rename = "et")]
    Et,
    #[serde(rename = "fk")]
    Fk,
    #[serde(rename = "fo")]
    Fo,
    #[serde(rename = "fj")]
    Fj,
    #[serde(rename = "fi")]
    Fi,
    #[serde(rename = "fr")]
    Fr,
    #[serde(rename = "gf")]
    Gf,
    #[serde(rename = "pf")]
    Pf,
    #[serde(rename = "tf")]
    Tf,
    #[serde(rename = "ga")]
    Ga,
    #[serde(rename = "gm")]
    Gm,
    #[serde(rename = "ge")]
    Ge,
    #[serde(rename = "de")]
    De,
    #[serde(rename = "gh")]
    Gh,
    #[serde(rename = "gi")]
    Gi,
    #[serde(rename = "gr")]
    Gr,
    #[serde(rename = "gl")]
    Gl,
    #[serde(rename = "gd")]
    Gd,
    #[serde(rename = "gp")]
    Gp,
    #[serde(rename = "gu")]
    Gu,
    #[serde(rename = "gt")]
    Gt,
    #[serde(rename = "gg")]
    Gg,
    #[serde(rename = "gn")]
    Gn,
    #[serde(rename = "gw")]
    Gw,
    #[serde(rename = "gy")]
    Gy,
    #[serde(rename = "ht")]
    Ht,
    #[serde(rename = "hm")]
    Hm,
    #[serde(rename = "va")]
    Va,
    #[serde(rename = "hn")]
    Hn,
    #[serde(rename = "hk")]
    Hk,
    #[serde(rename = "hu")]
    Hu,
    #[serde(rename = "is")]
    Is,
    #[serde(rename = "in")]
    In,
    #[serde(rename = "id")]
    Id,
    #[serde(rename = "ir")]
    Ir,
    #[serde(rename = "iq")]
    Iq,
    #[serde(rename = "ie")]
    Ie,
    #[serde(rename = "im")]
    Im,
    #[serde(rename = "il")]
    Il,
    #[serde(rename = "it")]
    It,
    #[serde(rename = "jm")]
    Jm,
    #[serde(rename = "jp")]
    Jp,
    #[serde(rename = "je")]
    Je,
    #[serde(rename = "jo")]
    Jo,
    #[serde(rename = "kz")]
    Kz,
    #[serde(rename = "ke")]
    Ke,
    #[serde(rename = "ki")]
    Ki,
    #[serde(rename = "kp")]
    Kp,
    #[serde(rename = "kr")]
    Kr,
    #[serde(rename = "kw")]
    Kw,
    #[serde(rename = "kg")]
    Kg,
    #[serde(rename = "la")]
    La,
    #[serde(rename = "lv")]
    Lv,
    #[serde(rename = "lb")]
    Lb,
    #[serde(rename = "ls")]
    Ls,
    #[serde(rename = "lr")]
    Lr,
    #[serde(rename = "ly")]
    Ly,
    #[serde(rename = "li")]
    Li,
    #[serde(rename = "lt")]
    Lt,
    #[serde(rename = "lu")]
    Lu,
    #[serde(rename = "mo")]
    Mo,
    #[serde(rename = "mg")]
    Mg,
    #[serde(rename = "mw")]
    Mw,
    #[serde(rename = "my")]
    My,
    #[serde(rename = "mv")]
    Mv,
    #[serde(rename = "ml")]
    Ml,
    #[serde(rename = "mt")]
    Mt,
    #[serde(rename = "mh")]
    Mh,
    #[serde(rename = "mq")]
    Mq,
    #[serde(rename = "mr")]
    Mr,
    #[serde(rename = "mu")]
    Mu,
    #[serde(rename = "yt")]
    Yt,
    #[serde(rename = "mx")]
    Mx,
    #[serde(rename = "fm")]
    Fm,
    #[serde(rename = "md")]
    Md,
    #[serde(rename = "mc")]
    Mc,
    #[serde(rename = "mn")]
    Mn,
    #[serde(rename = "me")]
    Me,
    #[serde(rename = "ms")]
    Ms,
    #[serde(rename = "ma")]
    Ma,
    #[serde(rename = "mz")]
    Mz,
    #[serde(rename = "mm")]
    Mm,
    #[serde(rename = "na")]
    Na,
    #[serde(rename = "nr")]
    Nr,
    #[serde(rename = "np")]
    Np,
    #[serde(rename = "nl")]
    Nl,
    #[serde(rename = "nc")]
    Nc,
    #[serde(rename = "nz")]
    Nz,
    #[serde(rename = "ni")]
    Ni,
    #[serde(rename = "ne")]
    Ne,
    #[serde(rename = "ng")]
    Ng,
    #[serde(rename = "nu")]
    Nu,
    #[serde(rename = "nf")]
    Nf,
    #[serde(rename = "mp")]
    Mp,
    #[serde(rename = "false")]
    False,
    #[serde(rename = "om")]
    Om,
    #[serde(rename = "pk")]
    Pk,
    #[serde(rename = "pw")]
    Pw,
    #[serde(rename = "ps")]
    Ps,
    #[serde(rename = "pa")]
    Pa,
    #[serde(rename = "pg")]
    Pg,
    #[serde(rename = "py")]
    Py,
    #[serde(rename = "pe")]
    Pe,
    #[serde(rename = "ph")]
    Ph,
    #[serde(rename = "pn")]
    Pn,
    #[serde(rename = "pl")]
    Pl,
    #[serde(rename = "pt")]
    Pt,
    #[serde(rename = "pr")]
    Pr,
    #[serde(rename = "qa")]
    Qa,
    #[serde(rename = "mk")]
    Mk,
    #[serde(rename = "ro")]
    Ro,
    #[serde(rename = "ru")]
    Ru,
    #[serde(rename = "rw")]
    Rw,
    #[serde(rename = "re")]
    Re,
    #[serde(rename = "bl")]
    Bl,
    #[serde(rename = "sh")]
    Sh,
    #[serde(rename = "kn")]
    Kn,
    #[serde(rename = "lc")]
    Lc,
    #[serde(rename = "mf")]
    Mf,
    #[serde(rename = "pm")]
    Pm,
    #[serde(rename = "vc")]
    Vc,
    #[serde(rename = "ws")]
    Ws,
    #[serde(rename = "sm")]
    Sm,
    #[serde(rename = "st")]
    St,
    #[serde(rename = "sa")]
    Sa,
    #[serde(rename = "sn")]
    Sn,
    #[serde(rename = "rs")]
    Rs,
    #[serde(rename = "sc")]
    Sc,
    #[serde(rename = "sl")]
    Sl,
    #[serde(rename = "sg")]
    Sg,
    #[serde(rename = "sx")]
    Sx,
    #[serde(rename = "sk")]
    Sk,
    #[serde(rename = "si")]
    Si,
    #[serde(rename = "sb")]
    Sb,
    #[serde(rename = "so")]
    So,
    #[serde(rename = "za")]
    Za,
    #[serde(rename = "gs")]
    Gs,
    #[serde(rename = "ss")]
    Ss,
    #[serde(rename = "es")]
    Es,
    #[serde(rename = "lk")]
    Lk,
    #[serde(rename = "sd")]
    Sd,
    #[serde(rename = "sr")]
    Sr,
    #[serde(rename = "sj")]
    Sj,
    #[serde(rename = "se")]
    Se,
    #[serde(rename = "ch")]
    Ch,
    #[serde(rename = "sy")]
    Sy,
    #[serde(rename = "tw")]
    Tw,
    #[serde(rename = "tj")]
    Tj,
    #[serde(rename = "tz")]
    Tz,
    #[serde(rename = "th")]
    Th,
    #[serde(rename = "tl")]
    Tl,
    #[serde(rename = "tg")]
    Tg,
    #[serde(rename = "tk")]
    Tk,
    #[serde(rename = "to")]
    To,
    #[serde(rename = "tt")]
    Tt,
    #[serde(rename = "tn")]
    Tn,
    #[serde(rename = "tr")]
    Tr,
    #[serde(rename = "tm")]
    Tm,
    #[serde(rename = "tc")]
    Tc,
    #[serde(rename = "tv")]
    Tv,
    #[serde(rename = "ug")]
    Ug,
    #[serde(rename = "ua")]
    Ua,
    #[serde(rename = "ae")]
    Ae,
    #[serde(rename = "gb")]
    Gb,
    #[serde(rename = "um")]
    Um,
    #[serde(rename = "us")]
    Us,
    #[serde(rename = "uy")]
    Uy,
    #[serde(rename = "uz")]
    Uz,
    #[serde(rename = "vu")]
    Vu,
    #[serde(rename = "ve")]
    Ve,
    #[serde(rename = "vn")]
    Vn,
    #[serde(rename = "vg")]
    Vg,
    #[serde(rename = "vi")]
    Vi,
    #[serde(rename = "wf")]
    Wf,
    #[serde(rename = "eh")]
    Eh,
    #[serde(rename = "ye")]
    Ye,
    #[serde(rename = "zm")]
    Zm,
    #[serde(rename = "zw")]
    Zw,
    #[serde(rename = "ax")]
    Ax,

}

impl std::fmt::Display for CountryCode {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Af => write!(f, "af"),
            Self::Al => write!(f, "al"),
            Self::Dz => write!(f, "dz"),
            Self::As => write!(f, "as"),
            Self::Ad => write!(f, "ad"),
            Self::Ao => write!(f, "ao"),
            Self::Ai => write!(f, "ai"),
            Self::Aq => write!(f, "aq"),
            Self::Ag => write!(f, "ag"),
            Self::Ar => write!(f, "ar"),
            Self::Am => write!(f, "am"),
            Self::Aw => write!(f, "aw"),
            Self::Au => write!(f, "au"),
            Self::At => write!(f, "at"),
            Self::Az => write!(f, "az"),
            Self::Bs => write!(f, "bs"),
            Self::Bh => write!(f, "bh"),
            Self::Bd => write!(f, "bd"),
            Self::Bb => write!(f, "bb"),
            Self::By => write!(f, "by"),
            Self::Be => write!(f, "be"),
            Self::Bz => write!(f, "bz"),
            Self::Bj => write!(f, "bj"),
            Self::Bm => write!(f, "bm"),
            Self::Bt => write!(f, "bt"),
            Self::Bo => write!(f, "bo"),
            Self::Bq => write!(f, "bq"),
            Self::Ba => write!(f, "ba"),
            Self::Bw => write!(f, "bw"),
            Self::Bv => write!(f, "bv"),
            Self::Br => write!(f, "br"),
            Self::Io => write!(f, "io"),
            Self::Bn => write!(f, "bn"),
            Self::Bg => write!(f, "bg"),
            Self::Bf => write!(f, "bf"),
            Self::Bi => write!(f, "bi"),
            Self::Cv => write!(f, "cv"),
            Self::Kh => write!(f, "kh"),
            Self::Cm => write!(f, "cm"),
            Self::Ca => write!(f, "ca"),
            Self::Ky => write!(f, "ky"),
            Self::Cf => write!(f, "cf"),
            Self::Td => write!(f, "td"),
            Self::Cl => write!(f, "cl"),
            Self::Cn => write!(f, "cn"),
            Self::Cx => write!(f, "cx"),
            Self::Cc => write!(f, "cc"),
            Self::Co => write!(f, "co"),
            Self::Km => write!(f, "km"),
            Self::Cd => write!(f, "cd"),
            Self::Cg => write!(f, "cg"),
            Self::Ck => write!(f, "ck"),
            Self::Cr => write!(f, "cr"),
            Self::Hr => write!(f, "hr"),
            Self::Cu => write!(f, "cu"),
            Self::Cw => write!(f, "cw"),
            Self::Cy => write!(f, "cy"),
            Self::Cz => write!(f, "cz"),
            Self::Ci => write!(f, "ci"),
            Self::Dk => write!(f, "dk"),
            Self::Dj => write!(f, "dj"),
            Self::Dm => write!(f, "dm"),
            Self::Do => write!(f, "do"),
            Self::Ec => write!(f, "ec"),
            Self::Eg => write!(f, "eg"),
            Self::Sv => write!(f, "sv"),
            Self::Gq => write!(f, "gq"),
            Self::Er => write!(f, "er"),
            Self::Ee => write!(f, "ee"),
            Self::Sz => write!(f, "sz"),
            Self::Et => write!(f, "et"),
            Self::Fk => write!(f, "fk"),
            Self::Fo => write!(f, "fo"),
            Self::Fj => write!(f, "fj"),
            Self::Fi => write!(f, "fi"),
            Self::Fr => write!(f, "fr"),
            Self::Gf => write!(f, "gf"),
            Self::Pf => write!(f, "pf"),
            Self::Tf => write!(f, "tf"),
            Self::Ga => write!(f, "ga"),
            Self::Gm => write!(f, "gm"),
            Self::Ge => write!(f, "ge"),
            Self::De => write!(f, "de"),
            Self::Gh => write!(f, "gh"),
            Self::Gi => write!(f, "gi"),
            Self::Gr => write!(f, "gr"),
            Self::Gl => write!(f, "gl"),
            Self::Gd => write!(f, "gd"),
            Self::Gp => write!(f, "gp"),
            Self::Gu => write!(f, "gu"),
            Self::Gt => write!(f, "gt"),
            Self::Gg => write!(f, "gg"),
            Self::Gn => write!(f, "gn"),
            Self::Gw => write!(f, "gw"),
            Self::Gy => write!(f, "gy"),
            Self::Ht => write!(f, "ht"),
            Self::Hm => write!(f, "hm"),
            Self::Va => write!(f, "va"),
            Self::Hn => write!(f, "hn"),
            Self::Hk => write!(f, "hk"),
            Self::Hu => write!(f, "hu"),
            Self::Is => write!(f, "is"),
            Self::In => write!(f, "in"),
            Self::Id => write!(f, "id"),
            Self::Ir => write!(f, "ir"),
            Self::Iq => write!(f, "iq"),
            Self::Ie => write!(f, "ie"),
            Self::Im => write!(f, "im"),
            Self::Il => write!(f, "il"),
            Self::It => write!(f, "it"),
            Self::Jm => write!(f, "jm"),
            Self::Jp => write!(f, "jp"),
            Self::Je => write!(f, "je"),
            Self::Jo => write!(f, "jo"),
            Self::Kz => write!(f, "kz"),
            Self::Ke => write!(f, "ke"),
            Self::Ki => write!(f, "ki"),
            Self::Kp => write!(f, "kp"),
            Self::Kr => write!(f, "kr"),
            Self::Kw => write!(f, "kw"),
            Self::Kg => write!(f, "kg"),
            Self::La => write!(f, "la"),
            Self::Lv => write!(f, "lv"),
            Self::Lb => write!(f, "lb"),
            Self::Ls => write!(f, "ls"),
            Self::Lr => write!(f, "lr"),
            Self::Ly => write!(f, "ly"),
            Self::Li => write!(f, "li"),
            Self::Lt => write!(f, "lt"),
            Self::Lu => write!(f, "lu"),
            Self::Mo => write!(f, "mo"),
            Self::Mg => write!(f, "mg"),
            Self::Mw => write!(f, "mw"),
            Self::My => write!(f, "my"),
            Self::Mv => write!(f, "mv"),
            Self::Ml => write!(f, "ml"),
            Self::Mt => write!(f, "mt"),
            Self::Mh => write!(f, "mh"),
            Self::Mq => write!(f, "mq"),
            Self::Mr => write!(f, "mr"),
            Self::Mu => write!(f, "mu"),
            Self::Yt => write!(f, "yt"),
            Self::Mx => write!(f, "mx"),
            Self::Fm => write!(f, "fm"),
            Self::Md => write!(f, "md"),
            Self::Mc => write!(f, "mc"),
            Self::Mn => write!(f, "mn"),
            Self::Me => write!(f, "me"),
            Self::Ms => write!(f, "ms"),
            Self::Ma => write!(f, "ma"),
            Self::Mz => write!(f, "mz"),
            Self::Mm => write!(f, "mm"),
            Self::Na => write!(f, "na"),
            Self::Nr => write!(f, "nr"),
            Self::Np => write!(f, "np"),
            Self::Nl => write!(f, "nl"),
            Self::Nc => write!(f, "nc"),
            Self::Nz => write!(f, "nz"),
            Self::Ni => write!(f, "ni"),
            Self::Ne => write!(f, "ne"),
            Self::Ng => write!(f, "ng"),
            Self::Nu => write!(f, "nu"),
            Self::Nf => write!(f, "nf"),
            Self::Mp => write!(f, "mp"),
            Self::False => write!(f, "false"),
            Self::Om => write!(f, "om"),
            Self::Pk => write!(f, "pk"),
            Self::Pw => write!(f, "pw"),
            Self::Ps => write!(f, "ps"),
            Self::Pa => write!(f, "pa"),
            Self::Pg => write!(f, "pg"),
            Self::Py => write!(f, "py"),
            Self::Pe => write!(f, "pe"),
            Self::Ph => write!(f, "ph"),
            Self::Pn => write!(f, "pn"),
            Self::Pl => write!(f, "pl"),
            Self::Pt => write!(f, "pt"),
            Self::Pr => write!(f, "pr"),
            Self::Qa => write!(f, "qa"),
            Self::Mk => write!(f, "mk"),
            Self::Ro => write!(f, "ro"),
            Self::Ru => write!(f, "ru"),
            Self::Rw => write!(f, "rw"),
            Self::Re => write!(f, "re"),
            Self::Bl => write!(f, "bl"),
            Self::Sh => write!(f, "sh"),
            Self::Kn => write!(f, "kn"),
            Self::Lc => write!(f, "lc"),
            Self::Mf => write!(f, "mf"),
            Self::Pm => write!(f, "pm"),
            Self::Vc => write!(f, "vc"),
            Self::Ws => write!(f, "ws"),
            Self::Sm => write!(f, "sm"),
            Self::St => write!(f, "st"),
            Self::Sa => write!(f, "sa"),
            Self::Sn => write!(f, "sn"),
            Self::Rs => write!(f, "rs"),
            Self::Sc => write!(f, "sc"),
            Self::Sl => write!(f, "sl"),
            Self::Sg => write!(f, "sg"),
            Self::Sx => write!(f, "sx"),
            Self::Sk => write!(f, "sk"),
            Self::Si => write!(f, "si"),
            Self::Sb => write!(f, "sb"),
            Self::So => write!(f, "so"),
            Self::Za => write!(f, "za"),
            Self::Gs => write!(f, "gs"),
            Self::Ss => write!(f, "ss"),
            Self::Es => write!(f, "es"),
            Self::Lk => write!(f, "lk"),
            Self::Sd => write!(f, "sd"),
            Self::Sr => write!(f, "sr"),
            Self::Sj => write!(f, "sj"),
            Self::Se => write!(f, "se"),
            Self::Ch => write!(f, "ch"),
            Self::Sy => write!(f, "sy"),
            Self::Tw => write!(f, "tw"),
            Self::Tj => write!(f, "tj"),
            Self::Tz => write!(f, "tz"),
            Self::Th => write!(f, "th"),
            Self::Tl => write!(f, "tl"),
            Self::Tg => write!(f, "tg"),
            Self::Tk => write!(f, "tk"),
            Self::To => write!(f, "to"),
            Self::Tt => write!(f, "tt"),
            Self::Tn => write!(f, "tn"),
            Self::Tr => write!(f, "tr"),
            Self::Tm => write!(f, "tm"),
            Self::Tc => write!(f, "tc"),
            Self::Tv => write!(f, "tv"),
            Self::Ug => write!(f, "ug"),
            Self::Ua => write!(f, "ua"),
            Self::Ae => write!(f, "ae"),
            Self::Gb => write!(f, "gb"),
            Self::Um => write!(f, "um"),
            Self::Us => write!(f, "us"),
            Self::Uy => write!(f, "uy"),
            Self::Uz => write!(f, "uz"),
            Self::Vu => write!(f, "vu"),
            Self::Ve => write!(f, "ve"),
            Self::Vn => write!(f, "vn"),
            Self::Vg => write!(f, "vg"),
            Self::Vi => write!(f, "vi"),
            Self::Wf => write!(f, "wf"),
            Self::Eh => write!(f, "eh"),
            Self::Ye => write!(f, "ye"),
            Self::Zm => write!(f, "zm"),
            Self::Zw => write!(f, "zw"),
            Self::Ax => write!(f, "ax"),
        }
    }
}

impl Default for CountryCode {
    fn default() -> CountryCode {
        Self::Af
    }
}

