/*
 * SaladCloud API
 *
 * The SaladCloud REST API. Please refer to the [SaladCloud API Documentation](https://docs.salad.com/api-reference) for more details.
 *
 * The version of the OpenAPI document: 0.9.0-alpha.17
 * Contact: cloud@salad.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CpuAvailabilityPrototype {
    /// A list of country codes where the resources are available
    #[serde(rename = "country_codes", skip_serializing_if = "Option::is_none")]
    pub country_codes: Option<Vec<models::CountryCode>>,
    /// The number of available CPU cores
    #[serde(rename = "cpu", skip_serializing_if = "Option::is_none")]
    pub cpu: Option<i32>,
    /// The amount of available memory in MB
    #[serde(rename = "memory", skip_serializing_if = "Option::is_none")]
    pub memory: Option<i64>,
    /// The amount of available storage in bytes
    #[serde(rename = "storage_amount", skip_serializing_if = "Option::is_none")]
    pub storage_amount: Option<i64>,
}

impl CpuAvailabilityPrototype {
    pub fn new() -> CpuAvailabilityPrototype {
        CpuAvailabilityPrototype {
            country_codes: None,
            cpu: None,
            memory: None,
            storage_amount: None,
        }
    }
}

