/*
 * SaladCloud API
 *
 * The SaladCloud REST API. Please refer to the [SaladCloud API Documentation](https://docs.salad.com/api-reference) for more details.
 *
 * The version of the OpenAPI document: 0.9.0-alpha.17
 * Contact: cloud@salad.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateContainerGroupNetworking : Network configuration for container groups specifying connectivity parameters, including authentication, protocol, and timeout settings
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateContainerGroupNetworking {
    /// Determines whether authentication is required for network connections to the container group
    #[serde(rename = "auth")]
    pub auth: bool,
    /// The container group networking client request timeout.
    #[serde(rename = "client_request_timeout", skip_serializing_if = "Option::is_none")]
    pub client_request_timeout: Option<i32>,
    #[serde(rename = "load_balancer", skip_serializing_if = "Option::is_none")]
    pub load_balancer: Option<models::ContainerGroupNetworkingLoadBalancer>,
    /// The container group networking port.
    #[serde(rename = "port")]
    pub port: i32,
    #[serde(rename = "protocol")]
    pub protocol: models::ContainerNetworkingProtocol,
    /// The container group networking server response timeout.
    #[serde(rename = "server_response_timeout", skip_serializing_if = "Option::is_none")]
    pub server_response_timeout: Option<i32>,
    /// The container group networking single connection limit flag.
    #[serde(rename = "single_connection_limit", skip_serializing_if = "Option::is_none")]
    pub single_connection_limit: Option<bool>,
}

impl CreateContainerGroupNetworking {
    /// Network configuration for container groups specifying connectivity parameters, including authentication, protocol, and timeout settings
    pub fn new(auth: bool, port: i32, protocol: models::ContainerNetworkingProtocol) -> CreateContainerGroupNetworking {
        CreateContainerGroupNetworking {
            auth,
            client_request_timeout: None,
            load_balancer: None,
            port,
            protocol,
            server_response_timeout: None,
            single_connection_limit: None,
        }
    }
}

