/*
 * SaladCloud API
 *
 * The SaladCloud REST API. Please refer to the [SaladCloud API Documentation](https://docs.salad.com/api-reference) for more details.
 *
 * The version of the OpenAPI document: 0.9.0-alpha.17
 * Contact: cloud@salad.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GpuClass : Represents a GPU Class
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GpuClass {
    /// The type of GPU class
    #[serde(rename = "gpu_class_type", skip_serializing_if = "Option::is_none")]
    pub gpu_class_type: Option<GpuClassType>,
    /// The number of GPUs in the cluster
    #[serde(rename = "gpu_count", skip_serializing_if = "Option::is_none")]
    pub gpu_count: Option<i32>,
    /// The unique identifier
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    /// Whether the GPU class is in high demand
    #[serde(rename = "is_high_demand", skip_serializing_if = "Option::is_none")]
    pub is_high_demand: Option<bool>,
    /// The maximum RAM amount in MB
    #[serde(rename = "max_ram", skip_serializing_if = "Option::is_none")]
    pub max_ram: Option<i32>,
    /// The maximum storage amount in bytes
    #[serde(rename = "max_storage", skip_serializing_if = "Option::is_none")]
    pub max_storage: Option<i64>,
    /// The maximum vCPU count
    #[serde(rename = "max_vcpu", skip_serializing_if = "Option::is_none")]
    pub max_vcpu: Option<i32>,
    /// The minimum RAM amount in MB
    #[serde(rename = "min_ram", skip_serializing_if = "Option::is_none")]
    pub min_ram: Option<i32>,
    /// The minimum storage amount in bytes
    #[serde(rename = "min_storage", skip_serializing_if = "Option::is_none")]
    pub min_storage: Option<i64>,
    /// The minimum vCPU count
    #[serde(rename = "min_vcpu", skip_serializing_if = "Option::is_none")]
    pub min_vcpu: Option<i32>,
    /// The GPU class name
    #[serde(rename = "name")]
    pub name: String,
    /// The list of prices for each container group priority
    #[serde(rename = "prices")]
    pub prices: Vec<models::GpuClassPrice>,
}

impl GpuClass {
    /// Represents a GPU Class
    pub fn new(id: uuid::Uuid, name: String, prices: Vec<models::GpuClassPrice>) -> GpuClass {
        GpuClass {
            gpu_class_type: None,
            gpu_count: None,
            id,
            is_high_demand: None,
            max_ram: None,
            max_storage: None,
            max_vcpu: None,
            min_ram: None,
            min_storage: None,
            min_vcpu: None,
            name,
            prices,
        }
    }
}
/// The type of GPU class
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum GpuClassType {
    #[serde(rename = "community")]
    Community,
    #[serde(rename = "secure")]
    Secure,
}

impl Default for GpuClassType {
    fn default() -> GpuClassType {
        Self::Community
    }
}

