/*
 * SaladCloud API
 *
 * The SaladCloud REST API. Please refer to the [SaladCloud API Documentation](https://docs.salad.com/api-reference) for more details.
 *
 * The version of the OpenAPI document: 0.9.0-alpha.17
 * Contact: cloud@salad.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GpuAvailability {
    /// The number of available GPU batches
    #[serde(rename = "available_gpu_batch", skip_serializing_if = "Option::is_none")]
    pub available_gpu_batch: Option<i32>,
    /// The number of available high-end GPUs
    #[serde(rename = "available_gpu_high", skip_serializing_if = "Option::is_none")]
    pub available_gpu_high: Option<i32>,
    /// The number of available low-end GPUs
    #[serde(rename = "available_gpu_low", skip_serializing_if = "Option::is_none")]
    pub available_gpu_low: Option<i32>,
    /// The number of available medium-end GPUs
    #[serde(rename = "available_gpu_medium", skip_serializing_if = "Option::is_none")]
    pub available_gpu_medium: Option<i32>,
    /// The number of on-call GPUs available
    #[serde(rename = "on_call_gpu", skip_serializing_if = "Option::is_none")]
    pub on_call_gpu: Option<i32>,
}

impl GpuAvailability {
    pub fn new() -> GpuAvailability {
        GpuAvailability {
            available_gpu_batch: None,
            available_gpu_high: None,
            available_gpu_low: None,
            available_gpu_medium: None,
            on_call_gpu: None,
        }
    }
}

