/*
 * SaladCloud API
 *
 * The SaladCloud REST API. Please refer to the [SaladCloud API Documentation](https://docs.salad.com/api-reference) for more details.
 *
 * The version of the OpenAPI document: 0.9.0-alpha.17
 * Contact: cloud@salad.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GpuClassPrice : Represents the price of a GPU class for a given container group priority
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GpuClassPrice {
    /// The price
    #[serde(rename = "price")]
    pub price: String,
    #[serde(rename = "priority", deserialize_with = "Option::deserialize")]
    pub priority: Option<models::ContainerGroupPriority>,
}

impl GpuClassPrice {
    /// Represents the price of a GPU class for a given container group priority
    pub fn new(price: String, priority: Option<models::ContainerGroupPriority>) -> GpuClassPrice {
        GpuClassPrice {
            price,
            priority,
        }
    }
}

