/*
 * SaladCloud API
 *
 * The SaladCloud REST API. Please refer to the [SaladCloud API Documentation](https://docs.salad.com/api-reference) for more details.
 *
 * The version of the OpenAPI document: 0.9.0-alpha.17
 * Contact: cloud@salad.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// InferenceEndpointJob : Represents a inference endpoint job
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InferenceEndpointJob {
    /// The time the job was created.
    #[serde(rename = "create_time")]
    pub create_time: time::OffsetDateTime,
    /// The list of events.
    #[serde(rename = "events")]
    pub events: Vec<models::InferenceEndpointJobEvent>,
    /// The inference endpoint job identifier.
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    /// The inference endpoint name.
    #[serde(rename = "inference_endpoint_name")]
    pub inference_endpoint_name: String,
    #[serde(rename = "input", deserialize_with = "Option::deserialize")]
    pub input: Option<serde_json::Value>,
    /// The job metadata. May be any valid JSON.
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<serde_json::Value>,
    /// The organization name.
    #[serde(rename = "organization_name")]
    pub organization_name: String,
    #[serde(rename = "output", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub output: Option<Option<serde_json::Value>>,
    #[serde(rename = "status")]
    pub status: models::InferenceEndpointJobStatus,
    /// The time the job was last updated.
    #[serde(rename = "update_time")]
    pub update_time: time::OffsetDateTime,
    /// The webhook URL called when the job completes.
    #[serde(rename = "webhook", skip_serializing_if = "Option::is_none")]
    pub webhook: Option<String>,
    /// The webhook URL called when the job completes.
    #[serde(rename = "webhook_url", skip_serializing_if = "Option::is_none")]
    pub webhook_url: Option<String>,
}

impl InferenceEndpointJob {
    /// Represents a inference endpoint job
    pub fn new(create_time: time::OffsetDateTime, events: Vec<models::InferenceEndpointJobEvent>, id: uuid::Uuid, inference_endpoint_name: String, input: Option<serde_json::Value>, organization_name: String, status: models::InferenceEndpointJobStatus, update_time: time::OffsetDateTime) -> InferenceEndpointJob {
        InferenceEndpointJob {
            create_time,
            events,
            id,
            inference_endpoint_name,
            input,
            metadata: None,
            organization_name,
            output: None,
            status,
            update_time,
            webhook: None,
            webhook_url: None,
        }
    }
}

