/*
 * SaladCloud API
 *
 * The SaladCloud REST API. Please refer to the [SaladCloud API Documentation](https://docs.salad.com/api-reference) for more details.
 *
 * The version of the OpenAPI document: 0.9.0-alpha.17
 * Contact: cloud@salad.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// InferenceEndpointJobEvent : Represents an event for inference endpoint job
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InferenceEndpointJobEvent {
    #[serde(rename = "action")]
    pub action: models::InferenceEndpointJobEventAction,
    /// The time the event occurred.
    #[serde(rename = "time")]
    pub time: time::OffsetDateTime,
}

impl InferenceEndpointJobEvent {
    /// Represents an event for inference endpoint job
    pub fn new(action: models::InferenceEndpointJobEventAction, time: time::OffsetDateTime) -> InferenceEndpointJobEvent {
        InferenceEndpointJobEvent {
            action,
            time,
        }
    }
}

