/*
 * SaladCloud API
 *
 * The SaladCloud REST API. Please refer to the [SaladCloud API Documentation](https://docs.salad.com/api-reference) for more details.
 *
 * The version of the OpenAPI document: 0.9.0-alpha.17
 * Contact: cloud@salad.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// InferenceEndpointJobPrototype : Represents a request to create a inference endpoint job
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InferenceEndpointJobPrototype {
    #[serde(rename = "input", deserialize_with = "Option::deserialize")]
    pub input: Option<serde_json::Value>,
    /// The job metadata. May be any valid JSON.
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<serde_json::Value>,
    /// The webhook URL to which the job results will be POSTed.
    #[serde(rename = "webhook", skip_serializing_if = "Option::is_none")]
    pub webhook: Option<String>,
    /// The webhook URL to which the job results will be POSTed.
    #[serde(rename = "webhook_url", skip_serializing_if = "Option::is_none")]
    pub webhook_url: Option<String>,
}

impl InferenceEndpointJobPrototype {
    /// Represents a request to create a inference endpoint job
    pub fn new(input: Option<serde_json::Value>) -> InferenceEndpointJobPrototype {
        InferenceEndpointJobPrototype {
            input,
            metadata: None,
            webhook: None,
            webhook_url: None,
        }
    }
}

