/*
 * SaladCloud API
 *
 * The SaladCloud REST API. Please refer to the [SaladCloud API Documentation](https://docs.salad.com/api-reference) for more details.
 *
 * The version of the OpenAPI document: 0.9.0-alpha.17
 * Contact: cloud@salad.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// InferenceEndpoint : Represents an inference endpoint
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InferenceEndpoint {
    /// The detailed description of the resource.
    #[serde(rename = "description")]
    pub description: String,
    /// The display-friendly name of the resource.
    #[serde(rename = "display_name")]
    pub display_name: String,
    /// The URL of the icon image
    #[serde(rename = "icon_url")]
    pub icon_url: String,
    /// The inference endpoint identifier.
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    /// The input schema
    #[serde(rename = "input_schema")]
    pub input_schema: String,
    /// The inference endpoint name.
    #[serde(rename = "name")]
    pub name: String,
    /// The organization name.
    #[serde(rename = "organization_name")]
    pub organization_name: String,
    /// The output schema
    #[serde(rename = "output_schema")]
    pub output_schema: String,
    /// A description of the price
    #[serde(rename = "price_description")]
    pub price_description: String,
    /// A markdown file containing a detailed description of the inference endpoint
    #[serde(rename = "readme")]
    pub readme: String,
}

impl InferenceEndpoint {
    /// Represents an inference endpoint
    pub fn new(description: String, display_name: String, icon_url: String, id: uuid::Uuid, input_schema: String, name: String, organization_name: String, output_schema: String, price_description: String, readme: String) -> InferenceEndpoint {
        InferenceEndpoint {
            description,
            display_name,
            icon_url,
            id,
            input_schema,
            name,
            organization_name,
            output_schema,
            price_description,
            readme,
        }
    }
}

