/*
 * SaladCloud API
 *
 * The SaladCloud REST API. Please refer to the [SaladCloud API Documentation](https://docs.salad.com/api-reference) for more details.
 *
 * The version of the OpenAPI document: 0.9.0-alpha.17
 * Contact: cloud@salad.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LogEntry {
    /// The log message in JSON format.
    #[serde(rename = "json_log", skip_serializing_if = "Option::is_none")]
    pub json_log: Option<std::collections::HashMap<String, serde_json::Value>>,
    /// The parent span ID of the log entry
    #[serde(rename = "parent_span_id", skip_serializing_if = "Option::is_none")]
    pub parent_span_id: Option<String>,
    /// The time when the log entry was received
    #[serde(rename = "receive_time")]
    pub receive_time: time::OffsetDateTime,
    #[serde(rename = "resource")]
    pub resource: Box<models::LogEntryResource>,
    #[serde(rename = "severity")]
    pub severity: models::LogEntrySeverity,
    /// The span ID of the log entry
    #[serde(rename = "span_Id", skip_serializing_if = "Option::is_none")]
    pub span_id: Option<String>,
    /// The log message in text format.
    #[serde(rename = "text_log", skip_serializing_if = "Option::is_none")]
    pub text_log: Option<String>,
    /// The timestamp of the log entry
    #[serde(rename = "time")]
    pub time: time::OffsetDateTime,
    /// The trace ID of the log entry
    #[serde(rename = "trace_Id", skip_serializing_if = "Option::is_none")]
    pub trace_id: Option<String>,
}

impl LogEntry {
    pub fn new(receive_time: time::OffsetDateTime, resource: models::LogEntryResource, severity: models::LogEntrySeverity, time: time::OffsetDateTime) -> LogEntry {
        LogEntry {
            json_log: None,
            parent_span_id: None,
            receive_time,
            resource: Box::new(resource),
            severity,
            span_id: None,
            text_log: None,
            time,
            trace_id: None,
        }
    }
}

