/*
 * SaladCloud API
 *
 * The SaladCloud REST API. Please refer to the [SaladCloud API Documentation](https://docs.salad.com/api-reference) for more details.
 *
 * The version of the OpenAPI document: 0.9.0-alpha.17
 * Contact: cloud@salad.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LogEntryCollection : Represents a page of organization logs
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LogEntryCollection {
    /// A collection of log entries
    #[serde(rename = "items")]
    pub items: Vec<models::LogEntry>,
    /// The organization name.
    #[serde(rename = "organization_name")]
    pub organization_name: String,
    /// The maximum time page boundary. This may be used when getting paginated results.
    #[serde(rename = "page_max_time")]
    pub page_max_time: time::OffsetDateTime,
    /// The minimum time page boundary. This may be used when getting paginated results.
    #[serde(rename = "page_min_time")]
    pub page_min_time: time::OffsetDateTime,
}

impl LogEntryCollection {
    /// Represents a page of organization logs
    pub fn new(items: Vec<models::LogEntry>, organization_name: String, page_max_time: time::OffsetDateTime, page_min_time: time::OffsetDateTime) -> LogEntryCollection {
        LogEntryCollection {
            items,
            organization_name,
            page_max_time,
            page_min_time,
        }
    }
}

