/*
 * SaladCloud API
 *
 * The SaladCloud REST API. Please refer to the [SaladCloud API Documentation](https://docs.salad.com/api-reference) for more details.
 *
 * The version of the OpenAPI document: 0.9.0-alpha.17
 * Contact: cloud@salad.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// QueueJob : Represents a queue job
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QueueJob {
    /// The job creation time
    #[serde(rename = "create_time")]
    pub create_time: time::OffsetDateTime,
    /// The job events
    #[serde(rename = "events")]
    pub events: Vec<models::QueueJobEvent>,
    /// The job identifier
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "input", deserialize_with = "Option::deserialize")]
    pub input: Option<serde_json::Value>,
    /// Additional metadata for the job
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<serde_json::Value>,
    #[serde(rename = "output", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub output: Option<Option<serde_json::Value>>,
    /// The job status
    #[serde(rename = "status")]
    pub status: Status,
    /// The job update time
    #[serde(rename = "update_time")]
    pub update_time: time::OffsetDateTime,
    /// The webhook URL to notify when the job completes
    #[serde(rename = "webhook", skip_serializing_if = "Option::is_none")]
    pub webhook: Option<String>,
}

impl QueueJob {
    /// Represents a queue job
    pub fn new(create_time: time::OffsetDateTime, events: Vec<models::QueueJobEvent>, id: uuid::Uuid, input: Option<serde_json::Value>, status: Status, update_time: time::OffsetDateTime) -> QueueJob {
        QueueJob {
            create_time,
            events,
            id,
            input,
            metadata: None,
            output: None,
            status,
            update_time,
            webhook: None,
        }
    }
}
/// The job status
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "running")]
    Running,
    #[serde(rename = "succeeded")]
    Succeeded,
    #[serde(rename = "cancelled")]
    Cancelled,
    #[serde(rename = "failed")]
    Failed,
}

impl Default for Status {
    fn default() -> Status {
        Self::Pending
    }
}

