/*
 * SaladCloud API
 *
 * The SaladCloud REST API. Please refer to the [SaladCloud API Documentation](https://docs.salad.com/api-reference) for more details.
 *
 * The version of the OpenAPI document: 0.9.0-alpha.17
 * Contact: cloud@salad.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// QueueJobPrototype : Represents a request to create a queue job
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QueueJobPrototype {
    #[serde(rename = "input", deserialize_with = "Option::deserialize")]
    pub input: Option<serde_json::Value>,
    /// Additional metadata for the job
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<serde_json::Value>,
    /// The webhook to call when the job completes
    #[serde(rename = "webhook", skip_serializing_if = "Option::is_none")]
    pub webhook: Option<String>,
}

impl QueueJobPrototype {
    /// Represents a request to create a queue job
    pub fn new(input: Option<serde_json::Value>) -> QueueJobPrototype {
        QueueJobPrototype {
            input,
            metadata: None,
            webhook: None,
        }
    }
}

