/*
 * SaladCloud API
 *
 * The SaladCloud REST API. Please refer to the [SaladCloud API Documentation](https://docs.salad.com/api-reference) for more details.
 *
 * The version of the OpenAPI document: 0.9.0-alpha.17
 * Contact: cloud@salad.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// QueueJobEvent : Represents an event for queue job
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QueueJobEvent {
    /// The action that was taken on the queue job
    #[serde(rename = "action")]
    pub action: Action,
    /// The time the action was taken on the queue job
    #[serde(rename = "time")]
    pub time: time::OffsetDateTime,
}

impl QueueJobEvent {
    /// Represents an event for queue job
    pub fn new(action: Action, time: time::OffsetDateTime) -> QueueJobEvent {
        QueueJobEvent {
            action,
            time,
        }
    }
}
/// The action that was taken on the queue job
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Action {
    #[serde(rename = "created")]
    Created,
    #[serde(rename = "started")]
    Started,
    #[serde(rename = "succeeded")]
    Succeeded,
    #[serde(rename = "cancelled")]
    Cancelled,
    #[serde(rename = "failed")]
    Failed,
}

impl Default for Action {
    fn default() -> Action {
        Self::Created
    }
}

