/*
 * SaladCloud API
 *
 * The SaladCloud REST API. Please refer to the [SaladCloud API Documentation](https://docs.salad.com/api-reference) for more details.
 *
 * The version of the OpenAPI document: 0.9.0-alpha.17
 * Contact: cloud@salad.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// QueuePrototype : Represents a request to create a new queue.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QueuePrototype {
    /// The description. This may be used as a space for notes or other information about the queue.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// The display name. This may be used as a more human-readable name.
    #[serde(rename = "display_name", skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    /// The queue name. This must be unique within the project.
    #[serde(rename = "name")]
    pub name: String,
}

impl QueuePrototype {
    /// Represents a request to create a new queue.
    pub fn new(name: String) -> QueuePrototype {
        QueuePrototype {
            description: None,
            display_name: None,
            name,
        }
    }
}

