/*
 * SaladCloud API
 *
 * The SaladCloud REST API. Please refer to the [SaladCloud API Documentation](https://docs.salad.com/api-reference) for more details.
 *
 * The version of the OpenAPI document: 0.9.0-alpha.17
 * Contact: cloud@salad.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SystemLogList : Represents a list of system logs
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SystemLogList {
    /// A list of system logs
    #[serde(rename = "items")]
    pub items: Vec<models::SystemLog>,
}

impl SystemLogList {
    /// Represents a list of system logs
    pub fn new(items: Vec<models::SystemLog>) -> SystemLogList {
        SystemLogList {
            items,
        }
    }
}

