/*
 * SaladCloud API
 *
 * The SaladCloud REST API. Please refer to the [SaladCloud API Documentation](https://docs.salad.com/api-reference) for more details.
 *
 * The version of the OpenAPI document: 0.9.0-alpha.17
 * Contact: cloud@salad.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UpdateContainer : Represents an update container object
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateContainer {
    /// Pass a command (and optional arguments) to override the ENTRYPOINT and CMD of a container image.
    #[serde(rename = "command", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub command: Option<Option<Vec<String>>>,
    /// Environment variables to set in the container.
    #[serde(rename = "environment_variables", skip_serializing_if = "Option::is_none")]
    pub environment_variables: Option<std::collections::HashMap<String, String>>,
    /// The container image to use.
    #[serde(rename = "image", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub image: Option<Option<String>>,
    /// The container image caching.
    #[serde(rename = "image_caching", skip_serializing_if = "Option::is_none")]
    pub image_caching: Option<bool>,
    #[serde(rename = "logging", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub logging: Option<Option<Box<models::UpdateContainerLogging>>>,
    #[serde(rename = "priority", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub priority: Option<Option<models::ContainerGroupPriority>>,
    #[serde(rename = "registry_authentication", skip_serializing_if = "Option::is_none")]
    pub registry_authentication: Option<Box<models::ContainerRegistryAuthentication>>,
    #[serde(rename = "resources", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub resources: Option<Option<Box<models::UpdateContainerResources>>>,
}

impl UpdateContainer {
    /// Represents an update container object
    pub fn new() -> UpdateContainer {
        UpdateContainer {
            command: None,
            environment_variables: None,
            image: None,
            image_caching: None,
            logging: None,
            priority: None,
            registry_authentication: None,
            resources: None,
        }
    }
}

