/*
 * SaladCloud API
 *
 * The SaladCloud REST API. Please refer to the [SaladCloud API Documentation](https://docs.salad.com/api-reference) for more details.
 *
 * The version of the OpenAPI document: 0.9.0-alpha.17
 * Contact: cloud@salad.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UpdateContainerResources : Defines the resource specifications that can be modified for a container group, including CPU, memory, GPU classes, and storage allocations.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateContainerResources {
    /// The number of CPU cores to allocate to the container (between 1 and 1024).
    #[serde(rename = "cpu", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub cpu: Option<Option<i32>>,
    /// List of GPU class identifiers that the container can use, specified as UUIDs.
    #[serde(rename = "gpu_classes", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub gpu_classes: Option<Option<Vec<uuid::Uuid>>>,
    /// The amount of memory to allocate to the container in megabytes (between 1024 and 1073741824).
    #[serde(rename = "memory", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub memory: Option<Option<i32>>,
    /// The amount of shared memory to allocate to the container via `/dev/shm` in megabytes (between 64 and 1073741824). If not specified, defaults to 64 MB.
    #[serde(rename = "shm_size", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub shm_size: Option<Option<i32>>,
    /// The amount of storage to allocate to the container in bytes (between 1 GB and 1 PB).
    #[serde(rename = "storage_amount", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub storage_amount: Option<Option<i64>>,
}

impl UpdateContainerResources {
    /// Defines the resource specifications that can be modified for a container group, including CPU, memory, GPU classes, and storage allocations.
    pub fn new() -> UpdateContainerResources {
        UpdateContainerResources {
            cpu: None,
            gpu_classes: None,
            memory: None,
            shm_size: None,
            storage_amount: None,
        }
    }
}

