/*
 * SaladCloud API
 *
 * The SaladCloud REST API. Please refer to the [SaladCloud API Documentation](https://docs.salad.com/api-reference) for more details.
 *
 * The version of the OpenAPI document: 0.9.0-alpha.17
 * Contact: cloud@salad.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WebhookSecretKey : Represents a webhook secret key
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebhookSecretKey {
    /// The webhook secret key
    #[serde(rename = "secret_key")]
    pub secret_key: String,
}

impl WebhookSecretKey {
    /// Represents a webhook secret key
    pub fn new(secret_key: String) -> WebhookSecretKey {
        WebhookSecretKey {
            secret_key,
        }
    }
}

