/*
 * SaladCloud API
 *
 * The SaladCloud REST API. Please refer to the [SaladCloud API Documentation](https://docs.salad.com/api-reference) for more details.
 *
 * The version of the OpenAPI document: 0.9.0-alpha.17
 * Contact: cloud@salad.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ContainerRegistryAuthentication : Authentication configuration for various container registry types, including AWS ECR, Docker Hub, GCP GAR, GCP GCR, and basic authentication.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContainerRegistryAuthentication {
    #[serde(
        rename = "aws_ecr",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    /// Field.
    pub aws_ecr: Option<Option<Box<models::ContainerRegistryAuthenticationAwsEcr>>>,
    #[serde(rename = "basic", skip_serializing_if = "Option::is_none")]
    /// Field.
    pub basic: Option<Box<models::ContainerRegistryAuthenticationBasic>>,
    #[serde(rename = "docker_hub", skip_serializing_if = "Option::is_none")]
    /// Field.
    pub docker_hub: Option<Box<models::ContainerRegistryAuthenticationDockerHub>>,
    #[serde(rename = "gcp_gar", skip_serializing_if = "Option::is_none")]
    /// Field.
    pub gcp_gar: Option<Box<models::ContainerRegistryAuthenticationGcpGar>>,
    #[serde(rename = "gcp_gcr", skip_serializing_if = "Option::is_none")]
    /// Field.
    pub gcp_gcr: Option<Box<models::ContainerRegistryAuthenticationGcpGcr>>,
}

impl ContainerRegistryAuthentication {
    /// Authentication configuration for various container registry types, including AWS ECR, Docker Hub, GCP GAR, GCP GCR, and basic authentication.
    pub fn new() -> ContainerRegistryAuthentication {
        ContainerRegistryAuthentication {
            aws_ecr: None,
            basic: None,
            docker_hub: None,
            gcp_gar: None,
            gcp_gcr: None,
        }
    }
}
