/*
 * SaladCloud API
 *
 * The SaladCloud REST API. Please refer to the [SaladCloud API Documentation](https://docs.salad.com/api-reference) for more details.
 *
 * The version of the OpenAPI document: 0.9.0-alpha.17
 * Contact: cloud@salad.com
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// ContainerRegistryAuthenticationDockerHub : Authentication details for Docker Hub registry
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContainerRegistryAuthenticationDockerHub {
    /// Docker Hub personal access token (PAT)
    #[serde(rename = "personal_access_token")]
    pub personal_access_token: String,
    /// Docker Hub username
    #[serde(rename = "username")]
    pub username: String,
}

impl ContainerRegistryAuthenticationDockerHub {
    /// Authentication details for Docker Hub registry
    pub fn new(
        personal_access_token: String,
        username: String,
    ) -> ContainerRegistryAuthenticationDockerHub {
        ContainerRegistryAuthenticationDockerHub {
            personal_access_token,
            username,
        }
    }
}
