/*
 * SaladCloud API
 *
 * The SaladCloud REST API. Please refer to the [SaladCloud API Documentation](https://docs.salad.com/api-reference) for more details.
 *
 * The version of the OpenAPI document: 0.9.0-alpha.17
 * Contact: cloud@salad.com
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// ContainerGroupQueueConnection : Configuration for connecting a container group to a message queue system, enabling asynchronous communication between services.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContainerGroupQueueConnection {
    /// The endpoint path for accessing the queue service, relative to the base URL of the queue server.
    #[serde(rename = "path")]
    pub path: String,
    /// The network port number used to connect to the queue service. Must be a valid TCP/IP port between 1 and 65535.
    #[serde(rename = "port")]
    pub port: i32,
    /// Unique identifier for the queue. Must start with a lowercase letter, can contain lowercase letters, numbers, and hyphens, and must end with a letter or number.
    #[serde(rename = "queue_name")]
    pub queue_name: String,
}

impl ContainerGroupQueueConnection {
    /// Configuration for connecting a container group to a message queue system, enabling asynchronous communication between services.
    pub fn new(path: String, port: i32, queue_name: String) -> ContainerGroupQueueConnection {
        ContainerGroupQueueConnection {
            path,
            port,
            queue_name,
        }
    }
}
