/*
 * SaladCloud API
 *
 * The SaladCloud REST API. Please refer to the [SaladCloud API Documentation](https://docs.salad.com/api-reference) for more details.
 *
 * The version of the OpenAPI document: 0.9.0-alpha.17
 * Contact: cloud@salad.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ContainerGroupProbeHttp : Defines HTTP probe configuration for container health checks within a container group.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContainerGroupProbeHttp {
    /// A collection of HTTP header name-value pairs used for configuring requests and responses in container group endpoints. Each header consists of a name and its corresponding value.
    #[serde(rename = "headers")]
    pub headers: Vec<models::ContainerGroupProbeHttpHeader>,
    /// The HTTP path that will be probed to check container health.
    #[serde(rename = "path")]
    pub path: String,
    /// The TCP port number to which the HTTP request will be sent.
    #[serde(rename = "port")]
    pub port: i32,
    #[serde(rename = "scheme", deserialize_with = "Option::deserialize")]
    /// Field.
    pub scheme: Option<models::ContainerProbeHttpScheme>,
}

impl ContainerGroupProbeHttp {
    /// Defines HTTP probe configuration for container health checks within a container group.
    pub fn new(
        headers: Vec<models::ContainerGroupProbeHttpHeader>,
        path: String,
        port: i32,
        scheme: Option<models::ContainerProbeHttpScheme>,
    ) -> ContainerGroupProbeHttp {
        ContainerGroupProbeHttp {
            headers,
            path,
            port,
            scheme,
        }
    }
}
