/*
 * SaladCloud API
 *
 * The SaladCloud REST API. Please refer to the [SaladCloud API Documentation](https://docs.salad.com/api-reference) for more details.
 *
 * The version of the OpenAPI document: 0.9.0-alpha.17
 * Contact: cloud@salad.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Container : Represents a container with its configuration and resource requirements.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Container {
    /// List of commands to run inside the container. Each command is a string representing a command-line instruction.
    #[serde(rename = "command", deserialize_with = "Option::deserialize")]
    pub command: Option<Vec<String>>,
    /// Environment variables to set in the container.
    #[serde(
        rename = "environment_variables",
        skip_serializing_if = "Option::is_none"
    )]
    pub environment_variables: Option<std::collections::HashMap<String, String>>,
    /// SHA-256 hash (64-character hexadecimal string)
    #[serde(rename = "hash", skip_serializing_if = "Option::is_none")]
    pub hash: Option<String>,
    /// The container image.
    #[serde(rename = "image")]
    pub image: String,
    /// The container image caching.
    #[serde(rename = "image_caching", skip_serializing_if = "Option::is_none")]
    pub image_caching: Option<bool>,
    #[serde(rename = "logging", skip_serializing_if = "Option::is_none")]
    /// Field.
    pub logging: Option<Box<models::ContainerLogging>>,
    #[serde(rename = "resources")]
    /// Field.
    pub resources: Box<models::ContainerResourceRequirements>,
    /// Size of the container in bytes.
    #[serde(rename = "size", skip_serializing_if = "Option::is_none")]
    pub size: Option<i64>,
}

impl Container {
    /// Represents a container with its configuration and resource requirements.
    pub fn new(
        command: Option<Vec<String>>,
        image: String,
        resources: models::ContainerResourceRequirements,
    ) -> Container {
        Container {
            command,
            environment_variables: None,
            hash: None,
            image,
            image_caching: None,
            logging: None,
            resources: Box::new(resources),
            size: None,
        }
    }
}
