/*
 * SaladCloud API
 *
 * The SaladCloud REST API. Please refer to the [SaladCloud API Documentation](https://docs.salad.com/api-reference) for more details.
 *
 * The version of the OpenAPI document: 0.9.0-alpha.17
 * Contact: cloud@salad.com
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// ContainerLoggingHttpFormat : The format in which logs will be delivered
/// The format in which logs will be delivered
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ContainerLoggingHttpFormat {
    #[serde(rename = "json")]
    /// Variant.
    Json,
    #[serde(rename = "json_lines")]
    /// Variant.
    JsonLines,
}

impl std::fmt::Display for ContainerLoggingHttpFormat {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Json => write!(f, "json"),
            Self::JsonLines => write!(f, "json_lines"),
        }
    }
}

impl Default for ContainerLoggingHttpFormat {
    fn default() -> ContainerLoggingHttpFormat {
        Self::Json
    }
}
