/*
 * SaladCloud API
 *
 * The SaladCloud REST API. Please refer to the [SaladCloud API Documentation](https://docs.salad.com/api-reference) for more details.
 *
 * The version of the OpenAPI document: 0.9.0-alpha.17
 * Contact: cloud@salad.com
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
/// Struct.
pub struct ContainerGroupProbeHttpHeader {
    /// The name of the HTTP header
    #[serde(rename = "name")]
    pub name: String,
    /// The value associated with the HTTP header
    #[serde(rename = "value")]
    pub value: String,
}

impl ContainerGroupProbeHttpHeader {
    /// Method / Function.
    pub fn new(name: String, value: String) -> ContainerGroupProbeHttpHeader {
        ContainerGroupProbeHttpHeader { name, value }
    }
}
