/*
 * SaladCloud API
 *
 * The SaladCloud REST API. Please refer to the [SaladCloud API Documentation](https://docs.salad.com/api-reference) for more details.
 *
 * The version of the OpenAPI document: 0.9.0-alpha.17
 * Contact: cloud@salad.com
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// ContainerRegistryAuthenticationAwsEcr : Authentication details for AWS Elastic Container Registry (ECR)
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContainerRegistryAuthenticationAwsEcr {
    /// AWS access key ID used for ECR authentication
    #[serde(rename = "access_key_id")]
    pub access_key_id: String,
    /// AWS secret access key used for ECR authentication
    #[serde(rename = "secret_access_key")]
    pub secret_access_key: String,
}

impl ContainerRegistryAuthenticationAwsEcr {
    /// Authentication details for AWS Elastic Container Registry (ECR)
    pub fn new(
        access_key_id: String,
        secret_access_key: String,
    ) -> ContainerRegistryAuthenticationAwsEcr {
        ContainerRegistryAuthenticationAwsEcr {
            access_key_id,
            secret_access_key,
        }
    }
}
