/*
 * SaladCloud API
 *
 * The SaladCloud REST API. Please refer to the [SaladCloud API Documentation](https://docs.salad.com/api-reference) for more details.
 *
 * The version of the OpenAPI document: 0.9.0-alpha.17
 * Contact: cloud@salad.com
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// ContainerGroupInstanceState : The state of the container group instance
/// The state of the container group instance
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ContainerGroupInstanceState {
    #[serde(rename = "allocating")]
    /// Variant.
    Allocating,
    #[serde(rename = "downloading")]
    /// Variant.
    Downloading,
    #[serde(rename = "creating")]
    /// Variant.
    Creating,
    #[serde(rename = "running")]
    /// Variant.
    Running,
    #[serde(rename = "stopping")]
    /// Variant.
    Stopping,
}

impl std::fmt::Display for ContainerGroupInstanceState {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Allocating => write!(f, "allocating"),
            Self::Downloading => write!(f, "downloading"),
            Self::Creating => write!(f, "creating"),
            Self::Running => write!(f, "running"),
            Self::Stopping => write!(f, "stopping"),
        }
    }
}

impl Default for ContainerGroupInstanceState {
    fn default() -> ContainerGroupInstanceState {
        Self::Allocating
    }
}
