/*
 * SaladCloud API
 *
 * The SaladCloud REST API. Please refer to the [SaladCloud API Documentation](https://docs.salad.com/api-reference) for more details.
 *
 * The version of the OpenAPI document: 0.9.0-alpha.17
 * Contact: cloud@salad.com
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// ContainerGroupInstanceStatusCount : A summary of container group instances categorized by their current lifecycle status
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContainerGroupInstanceStatusCount {
    /// The number of container instances that are currently being allocated resources
    #[serde(rename = "allocating_count")]
    pub allocating_count: i32,
    /// The number of container instances that are in the process of being created
    #[serde(rename = "creating_count")]
    pub creating_count: i32,
    /// The number of container instances that are currently running and operational
    #[serde(rename = "running_count")]
    pub running_count: i32,
    /// The number of container instances that are in the process of stopping
    #[serde(rename = "stopping_count")]
    pub stopping_count: i32,
}

impl ContainerGroupInstanceStatusCount {
    /// A summary of container group instances categorized by their current lifecycle status
    pub fn new(
        allocating_count: i32,
        creating_count: i32,
        running_count: i32,
        stopping_count: i32,
    ) -> ContainerGroupInstanceStatusCount {
        ContainerGroupInstanceStatusCount {
            allocating_count,
            creating_count,
            running_count,
            stopping_count,
        }
    }
}
