/*
 * SaladCloud API
 *
 * The SaladCloud REST API. Please refer to the [SaladCloud API Documentation](https://docs.salad.com/api-reference) for more details.
 *
 * The version of the OpenAPI document: 0.9.0-alpha.17
 * Contact: cloud@salad.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ContainerGroupState : Represents the operational state of a container group during its lifecycle, including timing information, status, and instance distribution metrics. This state captures the current execution status, start and finish times, and provides visibility into the operational health across instances.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContainerGroupState {
    /// Optional textual description or notes about the current state of the container group
    #[serde(
        rename = "description",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub description: Option<Option<String>>,
    /// Timestamp when the container group execution finished or is expected to finish
    #[serde(rename = "finish_time")]
    pub finish_time: time::OffsetDateTime,
    #[serde(rename = "instance_status_counts")]
    /// Field.
    pub instance_status_counts: Box<models::ContainerGroupInstanceStatusCount>,
    /// Timestamp when the container group execution started
    #[serde(rename = "start_time")]
    pub start_time: time::OffsetDateTime,
    #[serde(rename = "status")]
    /// Field.
    pub status: models::ContainerGroupStatus,
}

impl ContainerGroupState {
    /// Represents the operational state of a container group during its lifecycle, including timing information, status, and instance distribution metrics. This state captures the current execution status, start and finish times, and provides visibility into the operational health across instances.
    pub fn new(
        finish_time: time::OffsetDateTime,
        instance_status_counts: models::ContainerGroupInstanceStatusCount,
        start_time: time::OffsetDateTime,
        status: models::ContainerGroupStatus,
    ) -> ContainerGroupState {
        ContainerGroupState {
            description: None,
            finish_time,
            instance_status_counts: Box::new(instance_status_counts),
            start_time,
            status,
        }
    }
}
