/*
 * SaladCloud API
 *
 * The SaladCloud REST API. Please refer to the [SaladCloud API Documentation](https://docs.salad.com/api-reference) for more details.
 *
 * The version of the OpenAPI document: 0.9.0-alpha.17
 * Contact: cloud@salad.com
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// ContainerResourceRequirements : Specifies the resource requirements for a container.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContainerResourceRequirements {
    /// The number of CPU cores required by the container. Must be between 1 and 16.
    #[serde(rename = "cpu")]
    pub cpu: i32,
    /// A list of GPU class UUIDs required by the container. Can be null if no GPU is required.
    #[serde(rename = "gpu_classes")]
    pub gpu_classes: Vec<uuid::Uuid>,
    /// The amount of memory (in MB) required by the container. Must be between 1024 MB and 61440 MB.
    #[serde(rename = "memory")]
    pub memory: i32,
    /// The size of the shared memory (/dev/shm) in MB. If not specified, defaults to 1024MB.
    #[serde(rename = "shm_size", skip_serializing_if = "Option::is_none")]
    pub shm_size: Option<i32>,
    /// The amount of storage (in bytes) required by the container. Must be between 1 GB (1073741824 bytes) and 250 GB (268435456000 bytes).
    #[serde(rename = "storage_amount", skip_serializing_if = "Option::is_none")]
    pub storage_amount: Option<i64>,
}

impl ContainerResourceRequirements {
    /// Specifies the resource requirements for a container.
    pub fn new(
        cpu: i32,
        gpu_classes: Vec<uuid::Uuid>,
        memory: i32,
    ) -> ContainerResourceRequirements {
        ContainerResourceRequirements {
            cpu,
            gpu_classes,
            memory,
            shm_size: None,
            storage_amount: None,
        }
    }
}
