/*
 * SaladCloud API
 *
 * The SaladCloud REST API. Please refer to the [SaladCloud API Documentation](https://docs.salad.com/api-reference) for more details.
 *
 * The version of the OpenAPI document: 0.9.0-alpha.17
 * Contact: cloud@salad.com
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// ContainerLoggingHttpCompression : The compression algorithm to apply to logs before transmission
/// The compression algorithm to apply to logs before transmission
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
#[derive(Default)]
pub enum ContainerLoggingHttpCompression {
    #[serde(rename = "none")]
    /// Variant.
    #[default]
    None,
    #[serde(rename = "gzip")]
    /// Variant.
    Gzip,
}

impl std::fmt::Display for ContainerLoggingHttpCompression {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::None => write!(f, "none"),
            Self::Gzip => write!(f, "gzip"),
        }
    }
}

