/*
 * SaladCloud API
 *
 * The SaladCloud REST API. Please refer to the [SaladCloud API Documentation](https://docs.salad.com/api-reference) for more details.
 *
 * The version of the OpenAPI document: 0.9.0-alpha.17
 * Contact: cloud@salad.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ContainerGroupPatch : Represents a request to update a container group
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContainerGroupPatch {
    #[serde(
        rename = "container",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    /// Field.
    pub container: Option<Option<Box<models::UpdateContainer>>>,
    /// List of countries nodes must be located in. Remove this field to permit nodes from any country.
    #[serde(
        rename = "country_codes",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub country_codes: Option<Option<Vec<models::CountryCode>>>,
    /// The display name for the container group. If null is provided, the display name will be set to the container group name.
    #[serde(
        rename = "display_name",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub display_name: Option<Option<String>>,
    #[serde(
        rename = "liveness_probe",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    /// Field.
    pub liveness_probe: Option<Option<Box<models::ContainerGroupLivenessProbe>>>,
    #[serde(rename = "networking", skip_serializing_if = "Option::is_none")]
    /// Field.
    pub networking: Option<Box<models::UpdateContainerGroupNetworking>>,
    #[serde(rename = "queue_autoscaler", skip_serializing_if = "Option::is_none")]
    /// Field.
    pub queue_autoscaler: Option<Box<models::ContainerGroupQueueAutoscaler>>,
    #[serde(
        rename = "readiness_probe",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    /// Field.
    pub readiness_probe: Option<Option<Box<models::ContainerGroupReadinessProbe>>>,
    /// The desired number of instances for your container group deployment.
    #[serde(
        rename = "replicas",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub replicas: Option<Option<i32>>,
    /// List of scaling actions configurations
    #[serde(rename = "scaling-actions", skip_serializing_if = "Option::is_none")]
    pub scaling_actions: Option<Vec<models::ContainerGroupScalingAction>>,
    /// Indicates if scheduled scaling is enabled
    #[serde(
        rename = "scheduled-scaling-enabled",
        skip_serializing_if = "Option::is_none"
    )]
    pub scheduled_scaling_enabled: Option<bool>,
    #[serde(
        rename = "startup_probe",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    /// Field.
    pub startup_probe: Option<Option<Box<models::ContainerGroupStartupProbe>>>,
}

impl ContainerGroupPatch {
    /// Represents a request to update a container group
    pub fn new() -> ContainerGroupPatch {
        ContainerGroupPatch {
            container: None,
            country_codes: None,
            display_name: None,
            liveness_probe: None,
            networking: None,
            queue_autoscaler: None,
            readiness_probe: None,
            replicas: None,
            scaling_actions: None,
            scheduled_scaling_enabled: None,
            startup_probe: None,
        }
    }
}
