/*
 * SaladCloud API
 *
 * The SaladCloud REST API. Please refer to the [SaladCloud API Documentation](https://docs.salad.com/api-reference) for more details.
 *
 * The version of the OpenAPI document: 0.9.0-alpha.17
 * Contact: cloud@salad.com
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
/// Struct.
pub struct CpuAvailability {
    /// The number of available CPU cores
    #[serde(
        rename = "available_cpu_batch",
        skip_serializing_if = "Option::is_none"
    )]
    pub available_cpu_batch: Option<i32>,
    /// The amount of on-call CPU
    #[serde(rename = "on_call_cpu", skip_serializing_if = "Option::is_none")]
    pub on_call_cpu: Option<i32>,
}

impl CpuAvailability {
    /// Method / Function.
    pub fn new() -> CpuAvailability {
        CpuAvailability {
            available_cpu_batch: None,
            on_call_cpu: None,
        }
    }
}
