/*
 * SaladCloud API
 *
 * The SaladCloud REST API. Please refer to the [SaladCloud API Documentation](https://docs.salad.com/api-reference) for more details.
 *
 * The version of the OpenAPI document: 0.9.0-alpha.17
 * Contact: cloud@salad.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateContainerLoggingHttp : Configuration for sending container logs to an HTTP endpoint. Defines how logs are formatted, compressed, and transmitted.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateContainerLoggingHttp {
    #[serde(rename = "compression")]
    /// Field.
    pub compression: models::ContainerLoggingHttpCompression,
    #[serde(rename = "format")]
    /// Field.
    pub format: models::ContainerLoggingHttpFormat,
    /// Optional HTTP headers to include in log transmission requests
    #[serde(rename = "headers", skip_serializing_if = "Option::is_none")]
    pub headers: Option<Vec<models::ContainerLoggingHttpHeader>>,
    /// The hostname or IP address of the HTTP logging endpoint
    #[serde(rename = "host")]
    pub host: String,
    /// Optional password for HTTP authentication
    #[serde(
        rename = "password",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub password: Option<Option<String>>,
    /// Optional URL path for the HTTP endpoint
    #[serde(
        rename = "path",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub path: Option<Option<String>>,
    /// The port number of the HTTP logging endpoint (1-65535)
    #[serde(rename = "port")]
    pub port: i32,
    /// Optional username for HTTP authentication
    #[serde(
        rename = "user",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub user: Option<Option<String>>,
}

impl CreateContainerLoggingHttp {
    /// Configuration for sending container logs to an HTTP endpoint. Defines how logs are formatted, compressed, and transmitted.
    pub fn new(
        compression: models::ContainerLoggingHttpCompression,
        format: models::ContainerLoggingHttpFormat,
        host: String,
        port: i32,
    ) -> CreateContainerLoggingHttp {
        CreateContainerLoggingHttp {
            compression,
            format,
            headers: None,
            host,
            password: None,
            path: None,
            port,
            user: None,
        }
    }
}
