/*
 * SaladCloud API
 *
 * The SaladCloud REST API. Please refer to the [SaladCloud API Documentation](https://docs.salad.com/api-reference) for more details.
 *
 * The version of the OpenAPI document: 0.9.0-alpha.17
 * Contact: cloud@salad.com
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// InferenceEndpointJobStatus : The current status.
/// The current status.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum InferenceEndpointJobStatus {
    #[serde(rename = "pending")]
    /// Variant.
    Pending,
    #[serde(rename = "running")]
    /// Variant.
    Running,
    #[serde(rename = "succeeded")]
    /// Variant.
    Succeeded,
    #[serde(rename = "cancelled")]
    /// Variant.
    Cancelled,
    #[serde(rename = "failed")]
    /// Variant.
    Failed,
}

impl std::fmt::Display for InferenceEndpointJobStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Pending => write!(f, "pending"),
            Self::Running => write!(f, "running"),
            Self::Succeeded => write!(f, "succeeded"),
            Self::Cancelled => write!(f, "cancelled"),
            Self::Failed => write!(f, "failed"),
        }
    }
}

impl Default for InferenceEndpointJobStatus {
    fn default() -> InferenceEndpointJobStatus {
        Self::Pending
    }
}
