/*
 * SaladCloud API
 *
 * The SaladCloud REST API. Please refer to the [SaladCloud API Documentation](https://docs.salad.com/api-reference) for more details.
 *
 * The version of the OpenAPI document: 0.9.0-alpha.17
 * Contact: cloud@salad.com
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// InferenceEndpointJobEventAction : The action that was taken on the inference endpoint job.
/// The action that was taken on the inference endpoint job.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum InferenceEndpointJobEventAction {
    #[serde(rename = "created")]
    /// Variant.
    Created,
    #[serde(rename = "started")]
    /// Variant.
    Started,
    #[serde(rename = "succeeded")]
    /// Variant.
    Succeeded,
    #[serde(rename = "cancelled")]
    /// Variant.
    Cancelled,
    #[serde(rename = "failed")]
    /// Variant.
    Failed,
}

impl std::fmt::Display for InferenceEndpointJobEventAction {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Created => write!(f, "created"),
            Self::Started => write!(f, "started"),
            Self::Succeeded => write!(f, "succeeded"),
            Self::Cancelled => write!(f, "cancelled"),
            Self::Failed => write!(f, "failed"),
        }
    }
}

impl Default for InferenceEndpointJobEventAction {
    fn default() -> InferenceEndpointJobEventAction {
        Self::Created
    }
}
