/*
 * SaladCloud API
 *
 * The SaladCloud REST API. Please refer to the [SaladCloud API Documentation](https://docs.salad.com/api-reference) for more details.
 *
 * The version of the OpenAPI document: 0.9.0-alpha.17
 * Contact: cloud@salad.com
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// LogEntryResource : The resource associated with the log entry
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LogEntryResource {
    /// The labels associated with the resource
    #[serde(rename = "labels")]
    pub labels: std::collections::HashMap<String, String>,
    /// The type of the resource
    #[serde(rename = "type")]
    pub r#type: String,
}

impl LogEntryResource {
    /// The resource associated with the log entry
    pub fn new(
        labels: std::collections::HashMap<String, String>,
        r#type: String,
    ) -> LogEntryResource {
        LogEntryResource { labels, r#type }
    }
}
