/*
 * SaladCloud API
 *
 * The SaladCloud REST API. Please refer to the [SaladCloud API Documentation](https://docs.salad.com/api-reference) for more details.
 *
 * The version of the OpenAPI document: 0.9.0-alpha.17
 * Contact: cloud@salad.com
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// LogEntrySeverity : The severity level of the log entry
/// The severity level of the log entry
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum LogEntrySeverity {
    #[serde(rename = "default")]
    /// Variant.
    Default,
    #[serde(rename = "debug")]
    /// Variant.
    Debug,
    #[serde(rename = "info")]
    /// Variant.
    Info,
    #[serde(rename = "notice")]
    /// Variant.
    Notice,
    #[serde(rename = "warning")]
    /// Variant.
    Warning,
    #[serde(rename = "error")]
    /// Variant.
    Error,
    #[serde(rename = "critical")]
    /// Variant.
    Critical,
    #[serde(rename = "alert")]
    /// Variant.
    Alert,
    #[serde(rename = "emergency")]
    /// Variant.
    Emergency,
}

impl std::fmt::Display for LogEntrySeverity {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Default => write!(f, "default"),
            Self::Debug => write!(f, "debug"),
            Self::Info => write!(f, "info"),
            Self::Notice => write!(f, "notice"),
            Self::Warning => write!(f, "warning"),
            Self::Error => write!(f, "error"),
            Self::Critical => write!(f, "critical"),
            Self::Alert => write!(f, "alert"),
            Self::Emergency => write!(f, "emergency"),
        }
    }
}

impl Default for LogEntrySeverity {
    fn default() -> LogEntrySeverity {
        Self::Default
    }
}
