/*
 * SaladCloud API
 *
 * The SaladCloud REST API. Please refer to the [SaladCloud API Documentation](https://docs.salad.com/api-reference) for more details.
 *
 * The version of the OpenAPI document: 0.9.0-alpha.17
 * Contact: cloud@salad.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// QueueCollection : Represents a Queue Collection
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct QueueCollection {
    /// The list of queues.
    #[serde(rename = "items")]
    pub items: Vec<models::Queue>,
}

impl QueueCollection {
    /// Represents a Queue Collection
    pub fn new(items: Vec<models::Queue>) -> QueueCollection {
        QueueCollection { items }
    }
}
