/*
 * SaladCloud API
 *
 * The SaladCloud REST API. Please refer to the [SaladCloud API Documentation](https://docs.salad.com/api-reference) for more details.
 *
 * The version of the OpenAPI document: 0.9.0-alpha.17
 * Contact: cloud@salad.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Quotas : Represents the organization quotas
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Quotas {
    #[serde(rename = "container_groups_quotas")]
    /// Field.
    pub container_groups_quotas: Box<models::ContainerGroupsQuotas>,
    /// The time the resource was created
    #[serde(rename = "create_time", skip_serializing_if = "Option::is_none")]
    pub create_time: Option<time::OffsetDateTime>,
    /// The time the resource was last updated
    #[serde(rename = "update_time", skip_serializing_if = "Option::is_none")]
    pub update_time: Option<time::OffsetDateTime>,
}

impl Quotas {
    /// Represents the organization quotas
    pub fn new(container_groups_quotas: models::ContainerGroupsQuotas) -> Quotas {
        Quotas {
            container_groups_quotas: Box::new(container_groups_quotas),
            create_time: None,
            update_time: None,
        }
    }
}
