/*
 * SaladCloud API
 *
 * The SaladCloud REST API. Please refer to the [SaladCloud API Documentation](https://docs.salad.com/api-reference) for more details.
 *
 * The version of the OpenAPI document: 0.9.0-alpha.17
 * Contact: cloud@salad.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UpdateContainerLogging : Configuration options for directing container logs to a logging provider. This schema enables you to specify a single logging destination for container output, supporting monitoring, debugging, and analytics use cases. Each provider has its own configuration parameters defined in the referenced schemas. Only one logging provider can be selected at a time.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateContainerLogging {
    #[serde(rename = "axiom", skip_serializing_if = "Option::is_none")]
    /// Field.
    pub axiom: Option<Box<models::ContainerLoggingAxiom>>,
    #[serde(rename = "datadog", skip_serializing_if = "Option::is_none")]
    /// Field.
    pub datadog: Option<Box<models::ContainerLoggingDatadog>>,
    #[serde(rename = "http", skip_serializing_if = "Option::is_none")]
    /// Field.
    pub http: Option<Box<models::ContainerLoggingHttp>>,
    #[serde(rename = "new_relic", skip_serializing_if = "Option::is_none")]
    /// Field.
    pub new_relic: Option<Box<models::ContainerLoggingNewRelic>>,
    #[serde(rename = "splunk", skip_serializing_if = "Option::is_none")]
    /// Field.
    pub splunk: Option<Box<models::ContainerLoggingSplunk>>,
    #[serde(rename = "tcp", skip_serializing_if = "Option::is_none")]
    /// Field.
    pub tcp: Option<Box<models::ContainerLoggingTcp>>,
}

impl UpdateContainerLogging {
    /// Configuration options for directing container logs to a logging provider. This schema enables you to specify a single logging destination for container output, supporting monitoring, debugging, and analytics use cases. Each provider has its own configuration parameters defined in the referenced schemas. Only one logging provider can be selected at a time.
    pub fn new() -> UpdateContainerLogging {
        UpdateContainerLogging {
            axiom: None,
            datadog: None,
            http: None,
            new_relic: None,
            splunk: None,
            tcp: None,
        }
    }
}
